# Library

In [1]:
import sys
from pathlib import Path
import pandas as pd
# Asumsikan kamu menjalankan notebook dari 'data_pipeline_pyspark/notebooks'
# dan kamu ingin import dari 'data_pipeline_pyspark/src'
project_root = Path.cwd().parent
sys.path.append(str(project_root))

from dags.helper.profiling.profiling import Profiling
from dags.helper.profiling.extract_db import extract_database,extract_list_table
from dags.helper.profiling.config import stg_engine,wh_engine
from datetime import datetime

# Database

## Check Tabel

In [3]:
# Extract list of table in Database Startup Investments
list_table = extract_list_table()
list_table

       table_name
0           funds
1  funding_rounds
2            ipos
3          people
4         company
5     acquisition
6     investments
7   relationships
8      milestones

In [4]:
list_table_warehouse = extract_list_table(db_name='warehouse')
list_table_warehouse

                            table_name
0                           fact_funds
1                      fact_milestones
2                           dim_people
3                   fact_relationships
4                             dim_date
5  fact_investment_round_participation
6                          dim_company
7                     fact_acquisition
8                            fact_ipos

## Profiling Data Tabel Company

In [5]:
# Profiling Table Company
df_company = extract_database('company')

# create profiling object
company_profiling = Profiling(data = df_company, table_name='company')

# get columns from the table
company_profiling.get_columns()

['office_id',
 'object_id',
 'description',
 'region',
 'address1',
 'address2',
 'city',
 'zip_code',
 'state_code',
 'country_code',
 'latitude',
 'longitude',
 'created_at',
 'updated_at']

In [7]:
# Profiling Table Company
df_dim_company = extract_database('dim_company', db_name='warehouse')

# create profiling object
dim_company_profiling = Profiling(data = df_dim_company, table_name='dim_company')

# get columns from the table
dim_company_profiling.get_columns()

['company_id',
 'company_nk',
 'description',
 'region',
 'city',
 'state_code',
 'country_code',
 'latitude',
 'longitude',
 'created_at']

In [10]:
df_company.iloc[:5]

,office_id,object_id,description,region,address1,address2,city,zip_code,state_code,country_code,latitude,longitude,created_at,updated_at
0,127852,c:2862178,None,New York,735 State Street,San Francisco,BRIDGEWATER,10170,CA,USA,0.000000,0.000000,2025-07-29T06:00:00.000Z,2025-07-29T06:00:00.000Z
1,25,c:26,None,London,None,None,London,None,None,GBR,53.344104,-6.267494,2007-01-01T22:19:54.000Z,2007-01-01T22:19:54.000Z
2,154,c:157,None,Paris,None,None,Paris,None,None,FRA,48.856667,2.350987,2007-01-01T22:19:54.000Z,2007-01-01T22:19:54.000Z
3,623,c:636,None,United States - Other,None,None,None,None,None,USA,37.090240,-95.712891,2007-01-01T22:19:54.000Z,2007-01-01T22:19:54.000Z
4,1351,c:1374,None,London,None,None,London,None,None,GBR,51.500152,-0.126236,2007-01-01T22:19:54.000Z,2007-01-01T22:19:54.000Z

In [5]:
df_company.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95043 entries, 0 to 95042
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   office_id     95043 non-null  int64
 1   object_id     95043 non-null  object
 2   description   55377 non-null  object
 3   region        95043 non-null  object
 4   address1      79663 non-null  object
 5   address2      36740 non-null  object
 6   city          90683 non-null  object
 7   zip_code      79716 non-null  object
 8   state_code    54781 non-null  object
 9   country_code  95043 non-null  object
 10  latitude      95043 non-null  float64
 11  longitude     95043 non-null  float64
 12  created_at    95043 non-null  datetime64[ns]
 13  updated_at    95043 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1), object(9)
memory usage: 10.2+ MB

In [8]:
df_dim_company.iloc[:5]

,company_id,company_nk,description,region,city,state_code,country_code,latitude,longitude,created_at
0,1,c:26,None,London,London,N/A,GBR,53.3441,-6.267490,2025-07-29 16:33:31.893190+00:00
1,2,c:157,None,Paris,Paris,N/A,FRA,48.8567,2.350990,2025-07-29 16:33:31.893190+00:00
2,3,c:636,None,United States - Other,Unknown,N/A,USA,37.0902,-95.712900,2025-07-29 16:33:31.893190+00:00
3,4,c:1374,None,London,London,N/A,GBR,51.5002,-0.126236,2025-07-29 16:33:31.893190+00:00
4,5,c:1629,None,Tel Aviv,Tel-Aviv,N/A,ISR,32.0554,34.759500,2025-07-29 16:33:31.893190+00:00

In [9]:
df_dim_company.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95044 entries, 0 to 95043
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   company_id    95044 non-null  int64
 1   company_nk    95044 non-null  object
 2   description   55377 non-null  object
 3   region        95044 non-null  object
 4   city          95044 non-null  object
 5   state_code    95044 non-null  object
 6   country_code  95044 non-null  object
 7   latitude      95044 non-null  float64
 8   longitude     95044 non-null  float64
 9   created_at    95044 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(2), int64(1), object(6)
memory usage: 7.3+ MB

In [6]:
# Set Profiling Rule
# list check data type (all columns)
data_type_column = company_profiling.get_columns()

#list check unique values
unique_values = ['zip_code','state_code']

#list check percentage missing values
missing_values = ['description', 'address1', 'address2','city','zip_code','state_code']

#list check valid date values
valid_date = []

# Set Profiling rule to object
company_profiling.selected_columns(data_type_column, unique_values, missing_values, valid_date)

In [7]:
# Create Reporting Profiling
report_company = company_profiling.reporting()
report_company

{'created_at': '2025-04-06', 'report': {'office_id': {'data_type': 'int64'}, 'object_id': {'data_type': 'object'}, 'description': {'data_type': 'object', 'percentage_missing_value': 41.73}, 'region': {'data_type': 'object'}, 'address1': {'data_type': 'object', 'percentage_missing_value': 16.18}, 'address2': {'data_type': 'object', 'percentage_missing_value': 61.34}, 'city': {'data_type': 'object', 'percentage_missing_value': 4.59}, 'zip_code': {'data_type': 'object', 'unique_value': ['94070', '90069', '90232', '90210', '94103', nan, '94107', '92127', '94301', '90024', '95125', '10011-6903', '10036', '94089', '95134', '94108', 'SL7 2AF', '22182', '91101', '94102', '92121', '22107', '10019', '10016', '94005', '60601', '10012', '94085', '85281', '94104', '94017', '94041', '94105', '94043', 'L-2165', '94066', '90071', '52573', '10011', '10013', '94538', '06902', '94403', '60611', '98121', '13457', '94010', '91436', '94111', '94402', '94401', '10003', '27560', '02139', '91301', '75011', 'M2M 2W5', '95054', '98104', '78737', '1012LM', '1017TE', 'SO18 1NH', '95051', '94086', '98119', '94063', 'N1 6DL', '90401', '98109', '94114', '94501', '75017', '22033', '94941-2464', '02451', '60610', '94612', 'EC2A 4RQ', '94404', '53562', '75251', '10001', '94133', '1930', 'PA 19047', '94306-2123', '94022', '98122', '02116', '90048', '45230', '22902', '92130', '94410', '94303', '37950', '94109', '98070', '91364', '90036', '95032', '22209', '94941', '94965', '120-020', 'W2 1LA', '15222', '78746', '94566', 'E14 9TP', '95129', '98007', '48012', '94119-3152', '02110', '60607', '06901', '10018', '94025', '98005', '95113', '73134', '93108', 'BN1 9SB', '02108', '15601', '94501-1170', '1017 DR', '94611', '85060', '94025-1449', '48009', '43215', '94304', 'EC3N 4HJ', 'SE1 2JR', '2154', '21045', '131 52', '94017-1889', '98144', '10036-6518', '02142', '95008', '2909 LK', '94040', '92656', '10010', 'BC V1Y 9X1', '91521', '048545', '10024', '94304-1185', '14052', '90245', '30328', '94306', '42101', 'L4L 3T2', 'NY, 10601', '78205', '92651', '01950', '00130', 'LS12 1DR', '94111-5540', '90291', '3086448', '34109', '92663', '22201', '21119', '90064', '01460', '92056', '92101', '46032', '90028', '02138', '75034', '60626', '46733', 'W1J 7BU', '94608', '91503', '15259', '98052', '107-0052', '94401-4046', '19104', '80302', '19107', '15213', '02111', '94110', '27701', '55344', 'W1T 1QD', '95128', '10007', '8800', '90066', '02466', '45202', '76092', 'SW1H 0EA', '10014', '60661', '91367', '12240', '91206', 'W1S 2LQ', '33309', '20170', '94027', '94107-1537', '10004', '01810', '02452', '98006', '60606', '02215', '2200', '94107-1747', '98101', '80202', '310099', 'SW1E 5BH', '90292', '90404', 'BA1 2PH', 'BA1 2PW', '20876', '21230', '64112', '10115', 'M6B 1P5', '02109', 'V6E 4E5', '63104', '29708', '02906', 'NW1 0AG', '02453', 'WC1X 9HD', '01701', '90025', 'W1H 2EJ', 'EC2A 3DQ', '30092', '6001', '1616', '10038', '90056', '78730', '22790735', '20015', 'M2H 2L5', '0245902458', '90703', '02421', '38360', '1170', '91730', 'EC1N 8SS', '22314', '95014', '10023', '2862', '90010', 'CB1 2JX', 'SW1Y 4RX', '11109', '78731', '84062', '92606', '0', '22102', '80302-4839', '06320', '91403', '60654', '92037', '57000', '75008', 'M5T 2C8', '97209', '11695', '08003', 'H2X 2A1', '20852', '10969', '77382', '33701', '46725', '98075-7423', '83702', '33137', '75006', '02494', '98004', '02210', 'FIN-00045', '75231', '02129', 'EC1Y 2BP', '140-0002', '91362', '94065', '106-6161', '20910', 'KT6 7EL', '19312', '179098', '89120', '95030', '90293', '60972', '94707', '90275', '78745', '94530', '84117', '135011', 'e14', '94550', '94103-2812', '10600', '92075', '75062', '92009', '33127', '31672', 'E16JJ', '95070', '21224', 'W1T 2NS', '15203', '3204', '46586', '32901', '33404', 'T2P 4V5', '01748', '94103-5060', '80112', '90013', 'WC1E 7EB', '560 038', '94541', '98133', '10021', '01773', 'M5A 3S5', 'H3H1K4', '94710', '98034', '28050', '12601', '93100', '53-021', '97070', '07094-2419', '92122', '01267', '22844', '94062', '94042', '3056LK', '84604', '94121', '94582', 'WA4 4FS', '01710', '83130', 'EC1N 8TS', '10022', 'N1 6NG', '93403', '20815', 'EC4A 3AE', '94710-2219', '80209', '11215', 'V6X 1A7', '94117', '02886', '19428', '30024', 'C1428AQH', '12618', '2011 KN', '07670', 'DT2 7SA', '10011-2822', '97401', '00100', '75003', 'SW19 1QT', '55423', 'DK-2830', '48105', '95110', '19522', '1946', '94024', '90254', 'RG66AU', '02114', '20036', '30303', '64064', '55414-1035', '10017', '10178', '30346', '20120', 'CB3 0RD', '90049', 'M5C 2B8', '98103', '94141', '1360', '01720', 'H3B1A7', '32204', '18104', '100022', '94302', '08876', '53538', '84097', '78701-3217', '78701', '01760', '84003', '30326', 'SW19 6LU', '20850', '101-0024', '1016 DX', '94704', 'NW1 0EG', '07103', '46140', '20172', '60102', '94607', '94063-2026', '33731', '11229', '01824', '10605', 'M6P 4J2', '06514', '80111', 'AB T2G 1M8', '18015', '30332', 'N2L 6R5', '33134', '55347', '94309', 'CA', '200030', '08540', 'v6b1c6', '19406', 'V4R 0A5', 'HA5', '63118', 'CY-3608', '65816', '400051', '10008', '95826', 'M3H 5V3', '11101', 'T2G 0Y5', 'NN8 4PD', 'H4S 1E7', '10595', '84606', '11201', 'L9G4K9', '64081', '1075 HM', '75009', '200040', 'WC2E 9SB', '08002', '20457', '33418', '02141', '97006-6018', '01754', '94662', '113 24', '07601', '46158', '93940', '560008', '98105', '85260', '08854', '00000', '52521', '19085', '75002', '33301', '510665', '06824', '90405', '10016-8808', '60602', 'EH1 3EG', 'M6E1B5', '400 031', '10016-5602', '11231', '91105', '10005', 'PO6 3EN', '20165', '75225', '60401', '10706', '75016', '78756', '1327CB', '75081', 'CA 95134', '55124', '06854', '01803', '20009', '83616', '78744-1604', '01852', '02472', '77507', '2000', '95138', '33626', '02318', '08837', '37203', '40206', 'EC2M 6UR', '03060', '31000', '30605', '66213', 'CV7 9GX', '76375', '32779', '20190', '15219', '96817', '27101-4066', '02464', '02118', '01581-3961', '92023', '89173', '11735', '53186', '55413', '19103', '30339', '10175', '20007', '83642', '75007', '67442', '08861', '85024', '44000', '10119', '60008', '99622', '127083', '11577', 'WC2E 8HA', '08034', '616 00', '80603', 'K1S 5R5', '78758', 'OX4 2HN', '80005', '93063', '95035', '20354', '80211', '10006', '02445', '80919', '80304', '80335', '27588', 'V8V 1L1', '02476', '08011', '98102', 'V0N 1B6', 'V6A 1B2', '93117', '01730', '90027', '2232', '95112', '98104-2818', 'SE9 2RG', '11431', '95117', 'M5T 2C2', 'M4P 1E4', '0000', '94122', '94115', '06468', '60613', '17148', '1065', 'IP1 2QB', 'YO10 5ZD', 'SO140AA', '30377', '3511 HB', '81-055', 'HK', '08816', '560005', '11238', '80020', 'V5C 6G9', '60622', '94306-1827', 'M32 9AR', '97223', '4020', '12572', '92626', '98009', '95661', '33435', '98109-9267', '560 001', '59100', 'E1 6BT', '52522', '560049', '14231', '30097', '04043', '1017CB', 'E3C 2R2', '97005', '91103', 'M5V 1Y6', '30171', '75204', '43212', '29207', '0187', '90211', '78703', '75214', '3021 DD', '200020', '92694', '78759', '00202', '560070', 'W6 9HP', '07079', '02176', '90035', 'W1F 8HT', '08510', '34203', '08530', '400053', '510180', '400093', 'Dublin 2', '78705', 'V5Y1J5', 'SW6 3JD', '600095', '30075-2274', '04101', 'M5A4S7', 'EC1R 0DS', '21050-2747', '08542', '97214', '07003', 'B60 2JF', '27615', '18106', 'EC4A  3PJ', '53483', '15143', '68516', 'EH3 8JB', '75024', 'E1 6PL', '135-080', 'SE 164 51', 'W8 5QH', '20814', '97232', 'W1A 1AA', '78702', '32601', '32822', 'W4 1QP', 'SE-114 37', 'B3J 2B2', '90045', 'M5E 1K3', 'CB4 1DH', '33180', '94583', '02458', '15090', '94588', '60118', '52072', '95834', '08017', 'CT2 7FG', '89130', '19013', '22195', '35209', 'NO-0175', '78750', 'HON852', '2300 S', 'V8Z 7X8', '00790', '91406', '2010', '20171', '60428', '83000', '92604', 'NY 10003', '10163', '67016', '97701', '94065-1677', '11050-1210', '95762', '141300', '95131', '10997', '85705', '77388', '85018', 'M5S 1M2', '4558', '6830', '52100', '95061', 'M6R 2J5', '91106', '21017', '94063-1405', '94105-1420', '79000', 'NW5 4HY', '03038', '92807', '610041', '76040', 'PA16 8NG', 'N2J 1P8', '19714', 'G75 0QR', '100084', '30342', '92708', '380015', '41116', '20164', 'EC2A 4RJ', '92103', '33431', '89074', '10405', '85251', '01605', '92108', 'L4B3E4', '78666', '129226', '200219', '94949', '07086', '84042', '3162PL', '60061', 'H2W 1Y5', '1505', '92675', 'M4R1V2', '0104', '91316', '500 034', '87048', '73760', '90502', '75048', '32801', 'M5J 2L7', 'D - 80935', '20071', '500017', 'Fremont', '98296', '52556', '90057', '92603', '95811', '90077', '94127', '6051', 'W1F 7SP', '33487', '96822', 'EC1V 9QQ', '44691', 'RG8 7LR', '44643', '33710', '94118', '90029', '75015', 'W1U 4JT', 'E1 8DE', '78218', 'V6B 4N5', 'London', '92590', 'B9 4AA', '63303', '94123', '33156', '92008', '600 102', '43220', '07981', '3000', 'SW8 3XA', '34330', '43654', '22207', '110018', '15217', '30308', 'SE1 9PG', '06877', '94129', '600028', 'Dublin2', '29615', '12587', '11222', '92106', '78238', 'w1a 2hg', '67138', '641011', 'EC1M 5NP', '32257', '02420-4000', '68106', '84058', '020337', '1030', '20878', '21215', '01851', 'S11 8PE', '94043-2238', '10435', '380006', '98053', '6000', '13244', '10453', '69469', '75001', '27606', '22124', '94708', '98033', '37128', '11220', 'Nw1 8lh', 'H2T 1S5', '00230', '10961', '90408', 'EC2A 2BB', '20175', '93310', '37075', '1015', 'EC2A 4PF', '560038', '20740', 'T6E 6V7', '032566', 'V6B 5C6', '70176', 'M2P 2C9', 'N2H 6R4', 'E2L 1K2', '02144', 'M5V 1K4', '80204', '1058 AE', 'EC1M 5RF', 'EC2V 6DY', '55413-3017', '97204', '518057', 'CB4 1YG', '4001', '31300', 'IV12 5PR', '02134', '27707', '1456', 'EH3 9DQ', '76051', 'EN106QE', '94080', '110003', 'B-1000', '630055', 'TX', '91423', '29018', '20052', '80337', 'NW19RE', '28010', '9080', '500050', '78704', 'D-10179', '61574', '51371', 'E2 9PF', '44116', '20122', '30348', '02461', '37168', '7676', 'BS1 5HX', '02142-1209', '33126', '14623', '75013', '80021', '10701', '89107', '20006', '94039', '47403', 'D8', '64572', '42507', '90720', '2067', '65000', '54155', '10110', 'GU27 2JB', 'NW3 2PF', '1000', '630090', '89110', 'BS1 4TR', 'M9B 6B7', '80807', 'SE-111 43', 'EC2A 3HJ', '08753', '48103', '100080', 'SW3 3TY', 'V6B 1A1', '42677', 'W12 8YH', 'T5K 1B5', '45459', '1017 DS', '89109', '98273', '60188', 'N2J1P9', '46545', '34147', '8001', '3006', '078989', 'CB2 1NS', '380054', '79701', 'HP 4 2AB', 'V6B 0B7', 'WC1X 9LW', '17103', '08028', '9000', '1016 DW', 'SW8 1SJ', '84121', 'M2N7H2', '19355', 'SW11 2PB', 'EH3 7DX', 'GU14 6RF', '69710', 'K2K 3G4', '4575', '03062', '48109', '310012', '300162', 'SW1W 9SR', 'GU12 4RQ', 'EC1M 5UY', '40215', '35000', 'W6 7BJ', 'EC2A4RU', '21335', '94124', '75287', '32256', '22042', '45066', '50309', '30004', 'SE-113 47', 'T5J 3S4', '34360', '60647', '20008', '426011', '08018', 'NW19SA', 'W10 5BN', '37027', '98008', '08007', '28277', 'V6B 1R4', 'L1N 3G4', 'V6B 1G8', '95050', '27705', 'w6 8re', 'C1001AFB', '92109', '11042', '1051', '4000', '18974', '1015 BW', '08049-0001', '1015AP', '33765', '80301', '95439', '60657', '19809', '01845', '50825', '11214', '530013', 'M5G 1X3', 'M4W2K9', '92107', '10621', '00180', '7523 AA', 'm5j2y5', '02115', '28202', '89014', '20255', '08223', 'AB T5R 5Y3', '27708', 'W14 0DA', '11153', '95742', 'V6C 3G9', 'EC1Y 8QZ', '06484', '342006', '00008', '0753', '01002', '90038', '03249', '53703', '13522', 'M5C 2K4', '5000', '32504', '85717', '33323', '06856', '94087', '1435', '94107-4145', '60126', 'M4P 1L5', '2095 NSW', '1112ax', '318994', '84404', '07302', '803333', 'EH7 4LY', '11352', 'NG1 5FW', '01876', 'EC2A 1DX', '31412', '75082', '30309', '44700', 'N6A 5N6', '05404', '98225', 'G1S 1M3', '85013', 'CB1 1DP', 'SW4 0AY', 'BN44 3FN', '06880', '96821', '78258', '94301-1631', '22031', '22302', 'B-3910', '08904', '33608', '87231', '150-0001', '3156', '92011', '27603', 'NN18', '8005', '33004', '93433', '14526', '32960', '02481', '30326-3253', 'SA7 9ZJ', '30305', '14225', '27410', '4211', '75012', '92887', 'J4K 5G7', 'OX4 2PG', '19087', '20015-2601', '85258', 'E1 6JJ', '90017', '137-872', '6011', '122001', '201301', '67640', '98115', 'W10 5XL', 'sl71tu', 'TN2 5NP', '63177', '1050', 'S-417 56', '197373', '10002', '85719', '84094', '10524', '682025', 'E1C 4X7', '60515', '75093', '97213', '75069', '94952', '070000', '77036', '00144', '30338', '42300', '44221', '06085', '06018', 'TR140HX', 'M3C 1T5', 'M6K 1L3', '43607', '84020', 'NW1 0DU', '60652', '65785', '91302', 'NW8 9SP', '84047', '65189', '22085', '22761', '700091', '77057', '50823', 'SW6 1NZ', '22303', '55424', '11772', '20095', '90004', 'NE1 6EE', 'D12', 'M4P 1G4', '06890', '02459', '38106', 'TR15 2RZ', '02903', '94901', '47904', 'L4B 4B3', 'RH5 4QD', '33000', '29577', 'M2J 5B5', '78727', '93030', '424003', 'N2L 3W8', 'GU26 6LE', '122012', '86159', '29616-2162', 'SE17TP', 'EC2A 4LE', '10025', '94954', '904 22', '40258', 'M3B 1Z3', '02125', '10954', 'M4Y 1Z9', '97239', 'CA 90036', '90266', '02-797', 'DK-9000', '80797', '92612-8600', 'YO1 9WP', '90230', '100101', '90212', 'v6b2e2', '96743', '92038', '80601', 'SE1 7JB', 'T2W2X3', '411048', '20357', '92677', 'JE4 5KM', '18202', '10141', '79756', 'L3T 5M3', '28008', '8006', 'SE1 1YB', '20016', 'W1B 5TD', 'RG14 2FN', '3000AJ', 'W1D 3BW', '038988', 'L7M 3A4', 'W1U 2AR', '4837', '92110', '80031', '89436', '95610', '33130', '91356', '50010', '600020', '93012', '42781', '98292', '92600', '31044', '2312 PV', '600023', '98194', '80113', '411037', '10409', '02746', '1020', '110075', 'T2G 0X8', '90061', '48335', '29401', '1060', '77006', '90403', '91361', '21046', '97520', '12919', '98607-7671', '97225', '59741', '49503', '119021', '722 13', 'M5V 2W7', 'M3 4LQ', '2073', '33076', '1010', '75201', '55014', '94612-3611', '21202', '2119', '210005', 'M5V 1E3', 'M3 6BZ', '46614', 'M6H2B1', '8247', '8241', 'V6B 2M1', '94536', '97211', '13500', 'V6C 2T7', '08835', '91502', '27713', '84095', '66212', '75240', 'G1B 2G9', '95835', '27513', '97402', '84120', 'TN2 5TN', '14561', '06897', '71710', '1164', '1077', '81-1100 TibÃ¡s', '30268', '48071', '91608', '20359', '98373', 'H2S2M7', 'K1N 1J4', 'M5A 1S2', '1039', 'BS16 7AR', '20100', '38655', 'NN17 1AY', 'K1N 9N8', '33928', 'K2K 2M5', '3431HK', 'D-40221', '33154', 'm4l3j6', 'CH-8406', 'D14', '92010', 'SE11 4AN', 'V6B 6E3', '560004', '08039', '2795', '560078', '02600', '2690', '32765', '85286', 'SL1 7HZ', '92704', '46527', '34652', '91504', 'N1H 5R2', '30319', '03841', '49464', '105', '92618', 'L4W 5K4', '01302', '20459', '10509', '560043', 'AL4 0LA', '10243', '32746', '103-007', '95616', '75020', '44107', 'YO12 7NH', '169208', '06520', '60614', '3068', 'W1F 9DJ', '33469', '411029', '76133', '63141', '08035', '560047', 'KT2 6QJ', '76111', '62095', '94558', 'GA 30062', '17000', '101', '266000', '94002', 'SW6 3BU', '81577', '99100', '98125', '641043', 'M4P 3A2', '55811', 'L018', '43000', '90501', '55404', '50670', '84115', 'H3C 1L5', '91411', '01801', '560103', '54700', '20145', '2314VJ', 'TS15 9UE', '80339', 'V7V 3J3', '37923', '23431', '21701', '98036', '87102', '90051', '22203', '90503', '70112', '85252', '20147', '2065', 'E08009', '11460', '42400', '56860', '22767', '78716', 'C1A7K4', 'G1 1AA', '46528', 'M5V 2K6', 'W1T 3AB', '6865', '1018 KN', '3833 LC Leusden', 'WD63FG', '30161', '78249', '10245', '700511', '01702', '19047', '91385', '19147', '3110', 'RG6 1PT', 'RG41 5HE', '20004', '10118', '78701-3902', '94026-0999', 'W1S 3EP', '32826', 'L-1840', '10019-2701', 'SW1E 6DE', '80903', 'KY1-1103', '19004-1188', '03755', 'W1S 1BJ', '19004', 'EC1M 6EE', '80303', '08021', '4672562', '11021', 'WC2N 5JR', '10020', '10022-2605', 'V6E 3R5', 'H3B 5E7', 'V6C 2W2', '20037', '21202-1099', '94301-1922', '94304-1005', 'W1K 6TL', '94062-2448', '02266-8480', '16001', '06831', 'SW1E 5JD', 'CH-8700', '91789', '1001LH', '77072', 'M4P 2C9', 'W1J5AW', '81925', '10105', '10043', '92972', '80801', '02481-3800', '02062', '98112', '65224', '02199', '08014', 'DK-1260', '46120', '06830', '96067', '02142-1234', 'W8 5EH', 'P.R.C. 200040', '77010', '94939', '90067', '92648', '08084', '92037-3218', '60035', '94507', '169-0051', '103-0027', '10281-1198', '20005', '60018', 'M4T 1L8', 'EC3R 8ND', 'G6V 7N5', '2009', '22216', '21738', 'M5V 1J9', '19403', '127006', 'SW1E 6LD', '40202', '95052-8119', '80220', '01342', '67023', '17112', '75116', '02035', '84101', '43661', '7600', '67021', '55402', 'CB21 5XE', 'W1B 5DG', '44122', '10112', 'SW1Y 5JG', 'EC4M 7AN', '60606-2823', '01880', '91505', '560066', 'VIC', '85027', '038987', '18015-3715', '92692', '46204', 'M5H 1T1', '81739', 'W1F 9JG', 'EC2V 7ER', 'D-81679', '60325', 'H3B 2K8', '94028', '21227', '91481', 'M2N 6L7', '70174', 'TS10 1HH', '60062', 'N2G 4W1', 'N2J 4V1', '94061', '10019-3308', '10001-1129', '06905', 'NL-3723 HA', '100724', '11944', '17543', '10153', '3011', 'K2K 2X3', '10166', 'GY1 4HU', 'NSW 2000', 'BKR9037', '21409', '31401-2543', 'V6B 5L1', '35801', 'W1K 1RB', '32789', '94301-1648', 'W1J 5HB', '8022', 'W1B 5SE', '60604', '95110-2704', '01778', '103 89', '92612', '23225', '75205-2789', '46105', '94526', '400018', '60093', '06901-3236', '123056', 'EC2A 2JN', '80333', 'DK-1364', '06067', '89450-3215', 'M5G 1L7', 'M5H 3L5', 'N2L 1S7', '9004', '48104-1147', 'S-114 87', '22230', 'SW1H 9BP', '107-8077', '20004-2505', '07645', 'Nova Scotia', '95104', 'N6 5EU', '61175', '08648', '98404', '1071 DJ', 'Dubai', 'EC4A 1DE', 'W1G 0PW', 'L1510', '61378', '73104', '150-0022', 'PO15 5RQ', '90272', 'V6B 1C6', '50999', 'CH-6900', '14450', '95154', '11104', '91601', '400 710', '20251', '77007', '94159', '10075', 'PE11 4XF', '95031', '77046', '10999', '99101', '84043', '61614', 'IDF 92150', '92150', '63103', '64106', '20817', '05495', '80401-3306', '90046', '33308', '93612', '8014', '61032', '48226', '66505', '113 30', '85250', '78768-2136', 'B74 4BZ', 'CV1 2TT', 'V6B 2S2', 'T2P 1H7', 'N1E3B3', '6900', '94545', 'V6B 1H7', '52241', '30680', '110005', '91108', '1544BL', '80915', 'SE1 1EN', '92614', 'N6H 5X5', '97205', '58225', '85255', '33411', 'V7X 1K8', '94610', '560034', '34381', '77300', '1218', 'SL6 8AQ', 'NW3 3AJ', 'M1 7AB', '1019 GW', '1112 XH', '73072', '19026', '15120', '53711', '33133', '400056', '17602', '31310-260', 'M5V 2L3', '85022', '65806', '20001', '500082', '9701BC', '27617', '11211', '1012 KL', '8500', '1075BC', '80469', '34435', '069120', '6200', 'N6J 1Y5', 'SW1W 9TR', '77339', '17603', 'DE65 5FJ', 'SE1 0SU', '32233', '560097', '28290', '282028', '28043', '17674', '54307', '30067', '1205', '3030-199 Coimbra', '53713', '02122', 'M5V 2A2', 'EIRE', '32505', '05401', '64116', '33139', '93101', '01772', 'LE1 7RA', '43017', '80205', '79098', '33014', '78722', '4705-629', '92704-3424', '11100', '91011', '80290', '3024 EL', '14055', '10106', 'MK40 3PL', '34102', '30084', '97201', '4', '199034', '302019', '01930', 'V3J4G6', '08024', '03803', '1211', '22931-0108', '73000', '49601', '28044', '85257', 'A-1090', '80027', '201203', 'EC1R 4PF', '34390', '400701', '48073', '92300', 'V1X 7X6', 'DA15 7HB', '10504', '75080', '92263', '84102', 'W1F 8QP', '02169', '78248', 'i-3', '110', '08013', 'V6B1A1', '588376', 'B18 6BA', '3572PN', '540001', '400063', '80300', '55132', '78209', 'M1S 5B2', '3244', '28224', '7800', '03110', '91600', '92705', '91107', '47303', '41123', '94560', '66020', '60196', 'BC V5G 4E1', '48085', '2025', 'CA, 94103', '1466', '641012', 'CV1 4JU', 'E2K 4G4', '21209', '28173-6797', '94088', '408564', '400021', '103', '3521GH', 'W1W 8BD', 'H4C 2C7', '08191', 'DK-2605', '10566', 'SW13 9LE', '07024', 'V5Y 1P4', '2609', '78070', '107-006', '87114', '60313', '10533', '12489', '08108', '94129-0194', '92553', 'CB4 0WG', '80802', 'CH-8152', '85032-5582', '2111', 'SW8 3NP', '08201', 'sw7 2az', '4006', '3008', '6524', '10009', 'E1A 7Y1', 'N2L5H3', '96813', 'A-1101', '39104', '80030', '87501-2229', '20172-0447', 'W4 5YA', 'T2H0H3', '02143', '94123-1857', '1200-014', '641030', '51003', '13000', '1-03062,2-25009', '75022', '500072', '98011', '22655', '11745', 'SE1 3LE', 'EC2A 4BX', '81243', '02465', '8', '03101', '75074', 'D-04275', '91767', '22611', '08902', '01749', '3584 BH', 'WC1V 7QT', '19382', '0484', '07495', 

{'created_at': '2025-04-06',
 'report': {'office_id': {'data_type': 'int64'},
  'object_id': {'data_type': 'object'},
  'description': {'data_type': 'object', 'percentage_missing_value': 41.73},
  'region': {'data_type': 'object'},
  'address1': {'data_type': 'object', 'percentage_missing_value': 16.18},
  'address2': {'data_type': 'object', 'percentage_missing_value': 61.34},
  'city': {'data_type': 'object', 'percentage_missing_value': 4.59},
  'zip_code': {'data_type': 'object',
   'unique_value': ['94070',
    '90069',
    '90232',
    '90210',
    '94103',
    nan,
    '94107',
    '92127',
    '94301',
    '90024',
    '95125',
    '10011-6903',
    '10036',
    '94089',
    '95134',
    '94108',
    'SL7 2AF',
    '22182',
    '91101',
    '94102',
    '92121',
    '22107',
    '10019',
    '10016',
    '94005',
    '60601',
    '10012',
    '94085',
    '85281',
    '94104',
    '94017',
    '94041',
    '94105',
    '94043',
    'L-2165',
    '94066',
    '90071',
    '52573',
    '10011',
    '10013',
    '94538',
    '06902',
    '94403',
    '60611',
    '98121',
    '13457',
    '94010',
    '91436',
    '94111',
    '94402',
    '94401',
    '10003',
    '27560',
    '02139',
    '91301',
    '75011',
    'M2M 2W5',
    '95054',
    '98104',
    '78737',
    '1012LM',
    '1017TE',
    'SO18 1NH',
    '95051',
    '94086',
    '98119',
    '94063',
    'N1 6DL',
    '90401',
    '98109',
    '94114',
    '94501',
    '75017',
    '22033',
    '94941-2464',
    '02451',
    '60610',
    '94612',
    'EC2A 4RQ',
    '94404',
    '53562',
    '75251',
    '10001',
    '94133',
    '1930',
    'PA 19047',
    '94306-2123',
    '94022',
    '98122',
    '02116',
    '90048',
    '45230',
    '22902',
    '92130',
    '94410',
    '94303',
    '37950',
    '94109',
    '98070',
    '91364',
    '90036',
    '95032',
    '22209',
    '94941',
    '94965',
    '120-020',
    'W2 1LA',
    '15222',
    '78746',
    '94566',
    'E14 9TP',
    '95129',
    '98007',
    '48012',
    '94119-3152',
    '02110',
    '60607',
    '06901',
    '10018',
    '94025',
    '98005',
    '95113',
    '73134',
    '93108',
    'BN1 9SB',
    '02108',
    '15601',
    '94501-1170',
    '1017 DR',
    '94611',
    '85060',
    '94025-1449',
    '48009',
    '43215',
    '94304',
    'EC3N 4HJ',
    'SE1 2JR',
    '2154',
    '21045',
    '131 52',
    '94017-1889',
    '98144',
    '10036-6518',
    '02142',
    '95008',
    '2909 LK',
    '94040',
    '92656',
    '10010',
    'BC V1Y 9X1',
    '91521',
    '048545',
    '10024',
    '94304-1185',
    '14052',
    '90245',
    '30328',
    '94306',
    '42101',
    'L4L 3T2',
    'NY, 10601',
    '78205',
    '92651',
    '01950',
    '00130',
    'LS12 1DR',
    '94111-5540',
    '90291',
    '3086448',
    '34109',
    '92663',
    '22201',
    '21119',
    '90064',
    '01460',
    '92056',
    '92101',
    '46032',
    '90028',
    '02138',
    '75034',
    '60626',
    '46733',
    'W1J 7BU',
    '94608',
    '91503',
    '15259',
    '98052',
    '107-0052',
    '94401-4046',
    '19104',
    '80302',
    '19107',
    '15213',
    '02111',
    '94110',
    '27701',
    '55344',
    'W1T 1QD',
    '95128',
    '10007',
    '8800',
    '90066',
    '02466',
    '45202',
    '76092',
    'SW1H 0EA',
    '10014',
    '60661',
    '91367',
    '12240',
    '91206',
    'W1S 2LQ',
    '33309',
    '20170',
    '94027',
    '94107-1537',
    '10004',
    '01810',
    '02452',
    '98006',
    '60606',
    '02215',
    '2200',
    '94107-1747',
    '98101',
    '80202',
    '310099',
    'SW1E 5BH',
    '90292',
    '90404',
    'BA1 2PH',
    'BA1 2PW',
    '20876',
    '21230',
    '64112',
    '10115',
    'M6B 1P5',
    '02109',
    'V6E 4E5',
    '63104',
    '29708',
    '02906',
    'NW1 0AG',
    '02453',
    'WC1X 9HD',
    '01701',
    '90025',
    'W1H 2EJ',
    'EC2A 3DQ',
    '30092',
    '6001',
    '1616',
    '10038',
    '90056',
    '78730',
    '22790735',
    '20015',
    'M2H 2L5',
    '0245902458',
    '90703',
    '02421',
    '38360',
    '1170',
    '91730',
    'EC1N 8SS',
    '22314',
    '95014',
    '10023',
    '2862',
    '90010',
    'CB1 2JX',
    'SW1Y 4RX',
    '11109',
    '78731',
    '84062',
    '92606',
    '0',
    '22102',
    '80302-4839',
    '06320',
    '91403',
    '60654',
    '92037',
    '57000',
    '75008',
    'M5T 2C8',
    '97209',
    '11695',
    '08003',
    'H2X 2A1',
    '20852',
    '10969',
    '77382',
    '33701',
    '46725',
    '98075-7423',
    '83702',
    '33137',
    '75006',
    '02494',
    '98004',
    '02210',
    'FIN-00045',
    '75231',
    '02129',
    'EC1Y 2BP',
    '140-0002',
    '91362',
    '94065',
    '106-6161',
    '20910',
    'KT6 7EL',
    '19312',
    '179098',
    '89120',
    '95030',
    '90293',
    '60972',
    '94707',
    '90275',
    '78745',
    '94530',
    '84117',
    '135011',
    'e14',
    '94550',
    '94103-2812',
    '10600',
    '92075',
    '75062',
    '92009',
    '33127',
    '31672',
    'E16JJ',
    '95070',
    '21224',
    'W1T 2NS',
    '15203',
    '3204',
    '46586',
    '32901',
    '33404',
    'T2P 4V5',
    '01748',
    '94103-5060',
    '80112',
    '90013',
    'WC1E 7EB',
    '560 038',
    '94541',
    '98133',
    '10021',
    '01773',
    'M5A 3S5',
    'H3H1K4',
    '94710',
    '98034',
    '28050',
    '12601',
    '93100',
    '53-021',
    '97070',
    '07094-2419',
    '92122',
    '01267',
    '22844',
    '94062',
    '94042',
    '3056LK',
    '84604',
    '94121',
    '94582',
    'WA4 4FS',
    '01710',
    '83130',
    'EC1N 8TS',
    '10022',
    'N1 6NG',
    '93403',
    '20815',
    'EC4A 3AE',
    '94710-2219',
    '80209',
    '11215',
    'V6X 1A7',
    '94117',
    '02886',
    '19428',
    '30024',
    'C1428AQH',
    '12618',
    '2011 KN',
    '07670',
    'DT2 7SA',
    '10011-2822',
    '97401',
    '00100',
    '75003',
    'SW19 1QT',
    '55423',
    'DK-2830',
    '48105',
    '95110',
    '19522',
    '1946',
    '94024',
    '90254',
    'RG66AU',
    '02114',
    '20036',
    '30303',
    '64064',
    '55414-1035',
    '10017',
    '10178',
    '30346',
    '20120',
    'CB3 0RD',
    '90049',
    'M5C 2B8',
    '98103',
    '94141',
    '1360',
    '01720',
    'H3B1A7',
    '32204',
    '18104',
    '100022',
    '94302',
    '08876',
    '53538',
    '84097',
    '78701-3217',
    '78701',
    '01760',
    '84003',
    '30326',
    'SW19 6LU',
    '20850',
    '101-0024',
    '1016 DX',
    '94704',
    'NW1 0EG',
    '07103',
    '46140',
    '20172',
    '60102',
    '94607',
    '94063-2026',
    '33731',
    '11229',
    '01824',
    '10605',
    'M6P 4J2',
    '06514',
    '80111',
    'AB T2G 1M8',
    '18015',
    '30332',
    'N2L 6R5',
    '33134',
    '55347',
    '94309',
    'CA',
    '200030',
    '08540',
    'v6b1c6',
    '19406',
    'V4R 0A5',
    'HA5',
    '63118',
    'CY-3608',
    '65816',
    '400051',
    '10008',
    '95826',
    'M3H 5V3',
    '11101',
    'T2G 0Y5',
    'NN8 4PD',
    'H4S 1E7',
    '10595',
    '84606',
    '11201',
    'L9G4K9',
    '64081',
    '1075 HM',
    '75009',
    '200040',
    'WC2E 9SB',
    '08002',
    '20457',
    '33418',
    '02141',
    '97006-6018',
    '01754',
    '94662',
    '113 24',
    '07601',
    '46158',
    '93940',
    '560008',
    '98105',
    '85260',
    '08854',
    '00000',
    '52521',
    '19085',
    '75002',
    '33301',
    '510665',
    '06824',
    '90405',
    '10016-8808',
    '60602',
    'EH1 3EG',
    'M6E1B5',
    '400 031',
    '10016-5602',
    '11231',
    '91105',
    '10005',
    'PO6 3EN',
    '20165',
    '75225',
    '60401',
    '10706',
    '75016',
    '78756',
    '1327CB',
    '75081',
    'CA 95134',
    '55124',
    '06854',
    '01803',
    '20009',
    '83616',
    '78744-1604',
    '01852',
    '02472',
    '77507',
    '2000',
    '95138',
    '33626',
    '02318',
    '08837',
    '37203',
    '40206',
    'EC2M 6UR',
    '03060',
    '31000',
    '30605',
    '66213',
    'CV7 9GX',
    '76375',
    '32779',
    '20190',
    '15219',
    '96817',
    '27101-4066',
    '02464',
    '02118',
    '01581-3961',
    '92023',
    '89173',
    '11735',
    '53186',
    '55413',
    '19103',
    '30339',
    '10175',
    '20007',
    '83642',
    '75007',
    '67442',
    '08861',
    '85024',
    '44000',
    '10119',
    '60008',
    '99622',
    '127083',
    '11577',
    'WC2E 8HA',
    '08034',
    '616 00',
    '80603',
    'K1S 5R5',
    '78758',
    'OX4 2HN',
    '80005',
    '93063',
    '95035',
    '20354',
    '80211',
    '10006',
    '02445',
    '80919',
    '80304',
    '80335',
    '27588',
    'V8V 1L1',
    '02476',
    '08011',
    '98102',
    'V0N 1B6',
    'V6A 1B2',
    '93117',
    '01730',
    '90027',
    '2232',
    '95112',
    '98104-2818',
    'SE9 2RG',
    '11431',
    '95117',
    'M5T 2C2',
    'M4P 1E4',
    '0000',
    '94122',
    '94115',
    '06468',
    '60613',
    '17148',
    '1065',
    'IP1 2QB',
    'YO10 5ZD',
    'SO140AA',
    '30377',
    '3511 HB',
    '81-055',
    'HK',
    '08816',
    '560005',
    '11238',
    '80020',
    'V5C 6G9',
    '60622',
    '94306-1827',
    'M32 9AR',
    '97223',
    '4020',
    '12572',
    '92626',
    '98009',
    '95661',
    '33435',
    '98109-9267',
    '560 001',
    '59100',
    'E1 6BT',
    '52522',
    '560049',
    '14231',
    '30097',
    '04043',
    '1017CB',
    'E3C 2R2',
    '97005',
    '91103',
    'M5V 1Y6',
    '30171',
    '75204',
    '43212',
    '29207',
    '0187',
    '90211',
    '78703',
    '75214',
    '3021 DD',
    '200020',
    '92694',
    '78759',
    '00202',
    '560070',
    'W6 9HP',
    '07079',
    '02176',
    '90035',
    'W1F 8HT',
    '08510',
    '34203',
    '08530',
    '400053',
    '510180',
    '400093',
    'Dublin 2',
    '78705',
    'V5Y1J5',
    'SW6 3JD',
    '600095',
    '30075-2274',
    '04101',
    'M5A4S7',
    'EC1R 0DS',
    '21050-2747',
    '08542',
    '97214',
    '07003',
    'B60 2JF',
    '27615',
    '18106',
    'EC4A  3PJ',
    '53483',
    '15143',
    '68516',
    'EH3 8JB',
    '75024',
    'E1 6PL',
    '135-080',
    'SE 164 51',
    'W8 5QH',
    '20814',
    '97232',
    'W1A 1AA',
    '78702',
    '32601',
    '32822',
    'W4 1QP',
    'SE-114 37',
    'B3J 2B2',
    '90045',
    'M5E 1K3',
    'CB4 1DH',
    '33180',
    '94583',
    '02458',
    '15090',
    '94588',
    '60118',
    '52072',
    '95834',
    '08017',
    'CT2 7FG',
    '89130',
    '19013',
    '22195',
    '35209',
    'NO-0175',
    '78750',
    'HON852',
    '2300 S',
    'V8Z 7X8',
    '00790',
    '91406',
    '2010',
    '20171',
    '60428',
    '83000',
    '92604',
    'NY 10003',
    '10163',
    '67016',
    '97701',
    '94065-1677',
    '11050-1210',
    '95762',
    '141300',
    '95131',
    '10997',
    '85705',
    '77388',
    '85018',
    'M5S 1M2',
    '4558',
    '6830',
    '52100',
    '95061',
    'M6R 2J5',
    '91106',
    '21017',
    '94063-1405',
    '94105-1420',
    '79000',
    'NW5 4HY',
    '03038',
    '92807',
    '610041',
    '76040',
    'PA16 8NG',
    'N2J 1P8',
    '19714',
    'G75 0QR',
    '100084',
    '30342',
    '92708',
    '380015',
    '41116',
    '20164',
    'EC2A 4RJ',
    '92103',
    '33431',
    '89074',
    '10405',
    '85251',
    '01605',
    '92108',
    'L4B3E4',
    '78666',
    '129226',
    '200219',
    '94949',
    '07086',
    '84042',
    '3162PL',
    '60061',
    'H2W 1Y5',
    '1505',
    '92675',
    'M4R1V2',
    '0104',
    '91316',
    '500 034',
    '87048',
    '73760',
    '90502',
    '75048',
    '32801',
    'M5J 2L7',
    'D - 80935',
    '20071',
    '500017',
    'Fremont',
    '98296',
    '52556',
    '90057',
    '92603',
    '95811',
    '90077',
    '94127',
    '6051',
    'W1F 7SP',
    '33487',
    '96822',
    'EC1V 9QQ',
    '44691',
    'RG8 7LR',
    '44643',
    '33710',
    '94118',
    '90029',
    '75015',
    'W1U 4JT',
    'E1 8DE',
    '78218',
    'V6B 4N5',
    'London',
    '92590',
    'B9 4AA',
    '63303',
    '94123',
    '33156',
    '92008',
    '600 102',
    '43220',
    '07981',
    '3000',
    'SW8 3XA',
    '34330',
    '43654',
    '22207',
    '110018',
    '15217',
    '30308',
    'SE1 9PG',
    '06877',
    '94129',
    '600028',
    'Dublin2',
    '29615',
    '12587',
    '11222',
    '92106',
    '78238',
    'w1a 2hg',
    '67138',
    '641011',
    'EC1M 5NP',
    '32257',
    '02420-4000',
    '68106',
    '84058',
    '020337',
    '1030',
    '20878',
    '21215',
    '01851',
    'S11 8PE',
    '94043-2238',
    '10435',
    '380006',
    '98053',
    '6000',
    '13244',
    '10453',
    '69469',
    '75001',
    '27606',
    '22124',
    '94708',
    '98033',
    '37128',
    '11220',
    'Nw1 8lh',
    'H2T 1S5',
    '00230',
    '10961',
    '90408',
    'EC2A 2BB',
    '20175',
    '93310',
    '37075',
    '1015',
    'EC2A 4PF',
    '560038',
    '20740',
    'T6E 6V7',
    '032566',
    'V6B 5C6',
    '70176',
    'M2P 2C9',
    'N2H 6R4',
    'E2L 1K2',
    '02144',
    'M5V 1K4',
    '80204',
    '1058 AE',
    'EC1M 5RF',
    'EC2V 6DY',
    '55413-3017',
    '97204',
    '518057',
    'CB4 1YG',
    '4001',
    '31300',
    'IV12 5PR',
    '02134',
    '27707',
    '1456',
    'EH3 9DQ',
    '76051',
    'EN106QE',
    '94080',
    '110003',
    'B-1000',
    '630055',
    'TX',
    '91423',
    '29018',
    '20052',
    '80337',
    'NW19RE',
    '28010',
    '9080',
    '500050',
    '78704',
    'D-10179',
    '61574',
    '51371',
    'E2 9PF',
    '44116',
    '20122',
    '30348',
    '02461',
    '37168',
    '7676',
    'BS1 5HX',
    '02142-1209',
    '33126',
    '14623',
    '75013',
    '80021',
    '10701',
    '89107',
    '20006',
    '94039',
    '47403',
    'D8',
    '64572',
    '42507',
    '90720',
    '2067',
    '65000',
    '54155',
    '10110',
    'GU27 2JB',
    'NW3 2PF',
    '1000',
    '630090',
    '89110',
    'BS1 4TR',
    'M9B 6B7',
    '80807',
    'SE-111 43',
    'EC2A 3HJ',
    '08753',
    '48103',
    '100080',
    'SW3 3TY',
    ...],
   'percentage_missing_value': 16.13},
  'state_code': {'data_type': 'object',
   'unique_value': ['CA',
    nan,
    'NY',
    'VA',
    'TX',
    'IL',
    'AZ',
    'CT',
    'WA',
    'MA',
    'NC',
    'WI',
    'PA',
    'OH',
    'TN',
    'MD',
    'AL',
    'OK',
    'MI',
    'CO',
    'GA',
    'NV',
    'FL',
    'IN',
    'MN',
    'MO',
    'SC',
    'RI',
    'DC',
    'UT',
    'OR',
    'ID',
    'NJ',
    'NE',
    'ME',
    'KY',
    'NH',
    'KS',
    'HI',
    'DE',
    'NM',
    'IA',
    'AR',
    'VT',
    'SD',
    'MT',
    'MS',
    'LA',
    'AK',
    'WV',
    'WY',
    'ND'],
   'percentage_missing_value': 42.36},
  'country_code': {'data_type': 'object'},
  'latitude': {'data_type': 'float64'},
  'longitude': {'data_type': 'float64'},
  'created_at': {'data_type': 'datetime64[ns]'},
  'updated_at': {'data_type': 'datetime64[ns]'}}}

## Profiling Data Tabel Acquisition

In [15]:
# Profiling Table acquisition
df_acquisition = extract_database('acquisition')

# create profiling object
acquisition_profiling = Profiling(data = df_acquisition, table_name='acquisition')

# get columns from the table
acquisition_profiling.get_columns()

['acquisition_id',
 'acquiring_object_id',
 'acquired_object_id',
 'term_code',
 'price_amount',
 'price_currency_code',
 'acquired_at',
 'source_url',
 'source_description',
 'created_at',
 'updated_at']

In [12]:
# Profiling Table fact_acquisition
df_fact_acquisition = extract_database('fact_acquisition',db_name='warehouse')

# create profiling object
fact_acquisition_profiling = Profiling(data = df_fact_acquisition, table_name='fact_acquisition')

# get columns from the table
fact_acquisition_profiling.get_columns()

['acquisition_id',
 'acquisition_nk',
 'acquiring_company_id',
 'acquired_company_id',
 'acquired_at',
 'price_amount',
 'price_currency_code',
 'term_code',
 'created_at']

In [13]:
df_fact_acquisition

,acquisition_id,acquisition_nk,acquiring_company_id,acquired_company_id,acquired_at,price_amount,price_currency_code,term_code,created_at
0,1,2399,31645,31644,20080225,24370000.0,USD,Unknown,2025-07-29 16:49:07.264633+00:00
1,2,115,601,1501,20071201,0.0,USD,cash,2025-07-29 16:49:07.264633+00:00
2,3,996,26456,1672,20090406,0.0,USD,Unknown,2025-07-29 16:49:07.264633+00:00
3,4,2222,30911,30910,20080917,0.0,USD,Unknown,2025-07-29 16:49:07.264633+00:00
4,5,3336,601,33946,20100614,0.0,USD,Unknown,2025-07-29 16:49:07.264633+00:00
...,...,...,...,...,...,...,...,...,...
6326,6327,10065,1838,5612,20100624,0.0,USD,Unknown,2025-07-29 16:49:07.264633+00:00
6327,6328,10115,50708,25973,20110219,0.0,USD,Unknown,2025-07-29 16:49:07.264633+00:00
6328,6329,10137,254,7982,20131022,0.0,USD,Unknown,2025-07-29 16:49:07.264633+00:00
6329,6330,10179,12707,1483,20131029,0.0,USD,Unknown,2025-07-29 16:49:07.264633+00:00
6330,6331,10530,95044,95044,20131212,222000000.0,USD,cash,2025-07-31 14:30:36.409373+00:00

In [16]:
df_acquisition.iloc[:5]

,acquisition_id,acquiring_object_id,acquired_object_id,term_code,price_amount,price_currency_code,acquired_at,source_url,source_description,created_at,updated_at
0,10530,c:2862178,c:2862178,cash,222000000.00,USD,2013-12-12T00:00:00.000Z,http://techcrunch.com/2013/12/12/lifelock-acqu...,LifeLock Acquires Mobile Wallet Platform Lemon...,2025-07-29T06:00:00.000Z,2025-07-29T06:00:00.000Z
1,892,c:17503,c:2804,None,0.00,USD,2008-12-15T00:00:00.000Z,None,None,2009-01-21T21:38:51.000Z,2009-01-22T19:32:19.000Z
2,55,c:665,c:666,cash,255700000.00,USD,2005-12-01T00:00:00.000Z,None,None,2007-08-27T13:46:53.000Z,2008-02-25T00:23:49.000Z
3,56,c:11,c:667,cash,700000000.00,USD,2005-09-01T00:00:00.000Z,None,None,2007-08-27T13:54:40.000Z,2008-02-25T00:23:49.000Z
4,116,c:350,c:1611,cash,50000000.00,USD,1999-06-01T00:00:00.000Z,None,None,2007-12-17T15:49:24.000Z,2008-02-25T00:23:52.000Z

In [10]:
df_acquisition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6330 entries, 0 to 6329
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   acquisition_id       6330 non-null   int64
 1   acquiring_object_id  6330 non-null   object
 2   acquired_object_id   6330 non-null   object
 3   term_code            1160 non-null   object
 4   price_amount         6330 non-null   float64
 5   price_currency_code  6326 non-null   object
 6   acquired_at          6320 non-null   datetime64[ns]
 7   source_url           5855 non-null   object
 8   source_description   5874 non-null   object
 9   created_at           6330 non-null   datetime64[ns]
 10  updated_at           6330 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(1), int64(1), object(6)
memory usage: 544.1+ KB

In [17]:
df_fact_acquisition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6331 entries, 0 to 6330
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   acquisition_id        6331 non-null   int64
 1   acquisition_nk        6331 non-null   int64
 2   acquiring_company_id  6331 non-null   int64
 3   acquired_company_id   6331 non-null   int64
 4   acquired_at           6331 non-null   int64
 5   price_amount          6320 non-null   float64
 6   price_currency_code   6327 non-null   object
 7   term_code             6331 non-null   object
 8   created_at            6331 non-null   datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(1), int64(5), object(2)
memory usage: 445.3+ KB

In [11]:
# Set Profiling Rule
# list check data type (all columns)
data_type_column = acquisition_profiling.get_columns()

#list check unique values
unique_values = ['term_code','price_currency_code']

#list check percentage missing values
missing_values = ['term_code','price_currency_code', 'acquired_at', 'source_url','source_description']

#list check valid date values
valid_date = ['acquired_at']

# Set Profiling rule to object
acquisition_profiling.selected_columns(data_type_column, unique_values, missing_values, valid_date)

In [12]:
# Create Reporting Profiling
report_acquisition = acquisition_profiling.reporting()
report_acquisition

{'created_at': '2025-04-06', 'report': {'acquisition_id': {'data_type': 'int64'}, 'acquiring_object_id': {'data_type': 'object'}, 'acquired_object_id': {'data_type': 'object'}, 'term_code': {'data_type': 'object', 'unique_value': [nan, 'cash', 'stock', 'cash_and_stock'], 'percentage_missing_value': 81.67}, 'price_amount': {'data_type': 'float64'}, 'price_currency_code': {'data_type': 'object', 'unique_value': ['USD', 'EUR', 'CAD', nan, 'GBP', 'JPY'], 'percentage_missing_value': 0.06}, 'acquired_at': {'data_type': 'datetime64[ns]', 'percentage_missing_value': 0.16, 'percentage_valid_date': 99.84}, 'source_url': {'data_type': 'object', 'percentage_missing_value': 7.5}, 'source_description': {'data_type': 'object', 'percentage_missing_value': 7.2}, 'created_at': {'data_type': 'datetime64[ns]'}, 'updated_at': {'data_type': 'datetime64[ns]'}}}

{'created_at': '2025-04-06',
 'report': {'acquisition_id': {'data_type': 'int64'},
  'acquiring_object_id': {'data_type': 'object'},
  'acquired_object_id': {'data_type': 'object'},
  'term_code': {'data_type': 'object',
   'unique_value': [nan, 'cash', 'stock', 'cash_and_stock'],
   'percentage_missing_value': 81.67},
  'price_amount': {'data_type': 'float64'},
  'price_currency_code': {'data_type': 'object',
   'unique_value': ['USD', 'EUR', 'CAD', nan, 'GBP', 'JPY'],
   'percentage_missing_value': 0.06},
  'acquired_at': {'data_type': 'datetime64[ns]',
   'percentage_missing_value': 0.16,
   'percentage_valid_date': 99.84},
  'source_url': {'data_type': 'object', 'percentage_missing_value': 7.5},
  'source_description': {'data_type': 'object',
   'percentage_missing_value': 7.2},
  'created_at': {'data_type': 'datetime64[ns]'},
  'updated_at': {'data_type': 'datetime64[ns]'}}}

## Profiling Data Tabel funding_rounds

In [18]:
# Profiling Table funding_rounds
df_funding_rounds = extract_database('funding_rounds')

# create profiling object
funding_rounds_profiling = Profiling(data = df_funding_rounds, table_name='funding_rounds')

# get columns from the table
funding_rounds_profiling.get_columns()

['funding_round_id',
 'object_id',
 'funded_at',
 'funding_round_type',
 'funding_round_code',
 'raised_amount_usd',
 'raised_amount',
 'raised_currency_code',
 'pre_money_valuation_usd',
 'pre_money_valuation',
 'pre_money_currency_code',
 'post_money_valuation_usd',
 'post_money_valuation',
 'post_money_currency_code',
 'participants',
 'is_first_round',
 'is_last_round',
 'source_url',
 'source_description',
 'created_by',
 'created_at',
 'updated_at']

In [20]:
# Profiling Table fact_investment_round_participation
df_fact_investment_round_participation = extract_database('fact_investment_round_participation',db_name='warehouse')

# create profiling object
fact_investment_round_participation_profiling = Profiling(data = df_fact_investment_round_participation, table_name='fact_investment_round_participation')

# get columns from the table
fact_investment_round_participation_profiling.get_columns()

['investment_round_participation_id',
 'investment_nk',
 'funding_round_nk',
 'investee_company_id',
 'investor_company_id',
 'funded_at',
 'funding_round_type',
 'funding_round_code',
 'raised_amount',
 'pre_money_valuation',
 'post_money_valuation',
 'number_of_participants',
 'round_position_desc',
 'round_stage_desc',
 'created_at']

In [14]:
df_funding_rounds.iloc[:5]

,funding_round_id,object_id,funded_at,funding_round_type,funding_round_code,raised_amount_usd,raised_amount,raised_currency_code,pre_money_valuation_usd,pre_money_valuation,...,post_money_valuation,post_money_currency_code,participants,is_first_round,is_last_round,source_url,source_description,created_by,created_at,updated_at
0,1,c:4,2006-12-01,series-b,b,8500000.0,8500000.0,USD,0.0,0.0,...,0.0,NaN,2,False,False,http://www.marketingvox.com/archives/2006/12/2...,NaN,initial-importer,2007-07-04 04:52:57,2008-02-27 23:14:29
1,2,c:5,2004-09-01,angel,angel,500000.0,500000.0,USD,0.0,0.0,...,0.0,USD,2,False,False,NaN,NaN,initial-importer,2007-05-27 06:08:18,2013-06-28 20:07:23
2,3,c:5,2005-05-01,series-a,a,12700000.0,12700000.0,USD,115000000.0,115000000.0,...,0.0,USD,3,False,False,http://www.techcrunch.com/2007/11/02/jim-breye...,Jim Breyer: Extra $500 Million Round For Faceb...,initial-importer,2007-05-27 06:09:10,2013-06-28 20:07:23
3,4,c:5,2006-04-01,series-b,b,27500000.0,27500000.0,USD,525000000.0,525000000.0,...,0.0,USD,4,False,False,http://www.facebook.com/press/info.php?factsheet,Facebook Funding,initial-importer,2007-05-27 06:09:36,2013-06-28 20:07:24
4,5,c:7299,2006-05-01,series-b,b,10500000.0,10500000.0,USD,0.0,0.0,...,0.0,NaN,2,False,False,http://www.techcrunch.com/2006/05/14/photobuck...,PhotoBucket Closes $10.5M From Trinity Ventures,initial-importer,2007-05-29 11:05:59,2008-04-16 17:09:12

In [21]:
df_fact_investment_round_participation.iloc[:5]

,investment_round_participation_id,investment_nk,funding_round_nk,investee_company_id,investor_company_id,funded_at,funding_round_type,funding_round_code,raised_amount,pre_money_valuation,post_money_valuation,number_of_participants,round_position_desc,round_stage_desc,created_at
0,1,10321,7028,28105,28121,20080415,venture,unattributed,40000000.0,0.0,0.0,1.0,Not First Round,Ongoing Round,2025-07-29 16:47:34.301597+00:00
1,2,10972,7444,28763,29479,20090707,series-c+,c,20000000.0,0.0,0.0,4.0,Not First Round,Ongoing Round,2025-07-29 16:47:34.301597+00:00
2,3,10980,7448,28782,26860,20081112,venture,unattributed,21600000.0,0.0,0.0,3.0,Not First Round,Ongoing Round,2025-07-29 16:47:34.301597+00:00
3,4,11462,7697,11273,11274,20070829,series-b,b,26000000.0,0.0,0.0,5.0,Not First Round,Ongoing Round,2025-07-29 16:47:34.301597+00:00
4,5,11531,7744,29062,31187,20090915,series-a,a,4000000.0,0.0,0.0,3.0,Not First Round,Ongoing Round,2025-07-29 16:47:34.301597+00:00

In [22]:
df_fact_investment_round_participation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59407 entries, 0 to 59406
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   investment_round_participation_id  59407 non-null  int64
 1   investment_nk                      59407 non-null  int64
 2   funding_round_nk                   59407 non-null  int64
 3   investee_company_id                59407 non-null  int64
 4   investor_company_id                59407 non-null  int64
 5   funded_at                          59407 non-null  int64
 6   funding_round_type                 59407 non-null  object
 7   funding_round_code                 59407 non-null  object
 8   raised_amount                      59407 non-null  float64
 9   pre_money_valuation                59406 non-null  float64
 10  post_money_valuation               59407 non-null  float64
 11  number_of_participants             59407 non-null  float64
 12  round_position_desc                59407 non-null  object
 13  round_stage_desc                   59407 non-null  object
 14  created_at                         59407 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(4), int64(6), object(4)
memory usage: 6.8+ MB

In [15]:
df_funding_rounds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50182 entries, 0 to 50181
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   funding_round_id          50182 non-null  int64
 1   object_id                 50182 non-null  object
 2   funded_at                 49977 non-null  object
 3   funding_round_type        50182 non-null  object
 4   funding_round_code        50182 non-null  object
 5   raised_amount_usd         50182 non-null  float64
 6   raised_amount             50182 non-null  float64
 7   raised_currency_code      47479 non-null  object
 8   pre_money_valuation_usd   50182 non-null  float64
 9   pre_money_valuation       50182 non-null  float64
 10  pre_money_currency_code   26046 non-null  object
 11  post_money_valuation_usd  50182 non-null  float64
 12  post_money_valuation      50182 non-null  float64
 13  post_money_currency_code  29290 non-null  object
 14  participants              50182 non-null  object
 15  is_first_round            50182 non-null  bool
 16  is_last_round             50182 non-null  bool
 17  source_url                38969 non-null  object
 18  source_description        41684 non-null  object
 19  created_by                45928 non-null  object
 20  created_at                50182 non-null  datetime64[ns]
 21  updated_at                50182 non-null  datetime64[ns]
dtypes: bool(2), datetime64[ns](2), float64(6), int64(1), object(11)
memory usage: 7.8+ MB

In [16]:
# Set Profiling Rule
# list check data type (all columns)
data_type_column = funding_rounds_profiling.get_columns()

#list check unique values
unique_values = ['raised_currency_code','pre_money_currency_code','post_money_currency_code']

#list check percentage missing values
missing_values = ['funded_at','raised_currency_code', 'pre_money_currency_code', 
                  'post_money_currency_code','source_url','source_description','created_by']

#list check valid date values
valid_date = ['funded_at']

# Set Profiling rule to object
funding_rounds_profiling.selected_columns(data_type_column, unique_values, missing_values, valid_date)

In [ ]:
.info()

AttributeError: 'Profiling' object has no attribute 'info'

In [17]:
# Create Reporting Profiling
report_funding_rounds = funding_rounds_profiling.reporting()
report_funding_rounds

{'created_at': '2025-04-06', 'report': {'funding_round_id': {'data_type': 'int64'}, 'object_id': {'data_type': 'object'}, 'funded_at': {'data_type': 'object', 'percentage_missing_value': 0.41, 'percentage_valid_date': 99.59}, 'funding_round_type': {'data_type': 'object'}, 'funding_round_code': {'data_type': 'object'}, 'raised_amount_usd': {'data_type': 'float64'}, 'raised_amount': {'data_type': 'float64'}, 'raised_currency_code': {'data_type': 'object', 'unique_value': ['USD', nan, 'EUR', 'CAD', 'GBP', 'JPY', 'SEK', 'NIS', 'AUD'], 'percentage_missing_value': 5.39}, 'pre_money_valuation_usd': {'data_type': 'float64'}, 'pre_money_valuation': {'data_type': 'float64'}, 'pre_money_currency_code': {'data_type': 'object', 'unique_value': [nan, 'USD'], 'percentage_missing_value': 48.1}, 'post_money_valuation_usd': {'data_type': 'float64'}, 'post_money_valuation': {'data_type': 'float64'}, 'post_money_currency_code': {'data_type': 'object', 'unique_value': [nan, 'USD', 'SEK', 'EUR', 'GBP', 'CAD', 'JPY', 'AUD'], 'percentage_missing_value': 41.63}, 'participants': {'data_type': 'object'}, 'is_first_round': {'data_type': 'bool'}, 'is_last_round': {'data_type': 'bool'}, 'source_url': {'data_type': 'object', 'percentage_missing_value': 22.34}, 'source_description': {'data_type': 'object', 'percentage_missing_value': 16.93}, 'created_by': {'data_type': 'object', 'percentage_missing_value': 8.48}, 'created_at': {'data_type': 'datetime64[ns]'}, 'updated_at': {'data_type': 'datetime64[ns]'}}}

{'created_at': '2025-04-06',
 'report': {'funding_round_id': {'data_type': 'int64'},
  'object_id': {'data_type': 'object'},
  'funded_at': {'data_type': 'object',
   'percentage_missing_value': 0.41,
   'percentage_valid_date': 99.59},
  'funding_round_type': {'data_type': 'object'},
  'funding_round_code': {'data_type': 'object'},
  'raised_amount_usd': {'data_type': 'float64'},
  'raised_amount': {'data_type': 'float64'},
  'raised_currency_code': {'data_type': 'object',
   'unique_value': ['USD',
    nan,
    'EUR',
    'CAD',
    'GBP',
    'JPY',
    'SEK',
    'NIS',
    'AUD'],
   'percentage_missing_value': 5.39},
  'pre_money_valuation_usd': {'data_type': 'float64'},
  'pre_money_valuation': {'data_type': 'float64'},
  'pre_money_currency_code': {'data_type': 'object',
   'unique_value': [nan, 'USD'],
   'percentage_missing_value': 48.1},
  'post_money_valuation_usd': {'data_type': 'float64'},
  'post_money_valuation': {'data_type': 'float64'},
  'post_money_currency_code': {'data_type': 'object',
   'unique_value': [nan, 'USD', 'SEK', 'EUR', 'GBP', 'CAD', 'JPY', 'AUD'],
   'percentage_missing_value': 41.63},
  'participants': {'data_type': 'object'},
  'is_first_round': {'data_type': 'bool'},
  'is_last_round': {'data_type': 'bool'},
  'source_url': {'data_type': 'object', 'percentage_missing_value': 22.34},
  'source_description': {'data_type': 'object',
   'percentage_missing_value': 16.93},
  'created_by': {'data_type': 'object', 'percentage_missing_value': 8.48},
  'created_at': {'data_type': 'datetime64[ns]'},
  'updated_at': {'data_type': 'datetime64[ns]'}}}

## Profiling Data Tabel funds

In [27]:
# Profiling Table funds
df_funds = extract_database('funds')

# create profiling object
funds_profiling = Profiling(data = df_funds, table_name='funds')

# get columns from the table
funds_profiling.get_columns()

['fund_id',
 'object_id',
 'name',
 'funded_at',
 'raised_amount',
 'raised_currency_code',
 'source_url',
 'source_description',
 'created_at',
 'updated_at']

In [28]:
# Profiling Table fact_funds
df_fact_funds = extract_database('fact_funds',db_name='warehouse')

# create profiling object
fact_funds_profiling = Profiling(data = df_fact_funds, table_name='fact_funds')

# get columns from the table
fact_funds_profiling.get_columns()

['fund_id',
 'fund_nk',
 'company_id',
 'funded_at',
 'fund_name',
 'raised_amount',
 'raised_currency_code',
 'created_at']

In [19]:
df_funds.iloc[:5]

,fund_id,object_id,name,funded_at,raised_amount,raised_currency_code,source_url,source_description,created_at,updated_at
0,1,f:371,Second Fund,2008-12-16,300000000.0,USD,http://www.pehub.com/26194/dfj-dragon-raising-...,peHub,2008-12-17 03:07:16,2008-12-17 03:07:16
1,4,f:17,Sequoia Israel Fourth Fund,2008-12-17,200750000.0,USD,http://www.pehub.com/26725/sequoia-israel-rais...,Sequoia Israel Raises Fourth Fund,2008-12-18 22:04:42,2008-12-18 22:04:42
2,5,f:951,Tenth fund,2008-08-11,650000000.0,USD,http://venturebeat.com/2008/08/11/interwest-cl...,Venture Beat,2008-12-31 09:47:51,2008-12-31 09:47:51
3,6,f:192,New funds acquire,None,625000000.0,USD,http://venturebeat.com/2008/07/28/us-venture-p...,U.S. Venture Partners raises $625M fund for ne...,2009-01-01 18:13:44,2009-01-01 18:16:27
4,7,f:519,Third fund,2008-05-20,200000000.0,USD,http://venturebeat.com/2008/05/20/disneys-stea...,Venture Beat,2009-01-03 09:51:58,2013-09-03 16:34:54

In [52]:
df_fact_funds['raised_currency_code'].value_counts()

raised_currency_code
USD    1238
EUR     171
GBP      67
CAD      11
JPY       3
AUD       2
SEK       1
Name: count, dtype: int64

In [51]:
df_funds[df_funds['fund_id']=='97']

,fund_id,object_id,name,funded_at,raised_amount,raised_currency_code,source_url,source_description,created_at,updated_at
103,97,f:4,Accel Fund,2008-12-01,10000000000.00,USD,http://stephenlaughlin.posterous.com/index-ven...,Index Ventures Raises $440 Million for Tech Fund,2009-10-22T22:43:59.000Z,2012-06-27T21:30:37.000Z

In [41]:
df_fact_funds[df_fact_funds['raised_amount'].isna()]

,fund_id,fund_nk,company_id,funded_at,fund_name,raised_amount,raised_currency_code,created_at
70,71,97,3819,20081201,Accel Fund,NaN,USD,2025-07-29 16:46:42.229846+00:00
117,118,740,10038,20120403,Venture Fund 2012,NaN,USD,2025-07-29 16:46:42.229846+00:00
505,506,1100,26861,20130419,Silver Lake Partners IV,NaN,USD,2025-07-29 16:46:42.229846+00:00
691,691,1443,75449,20130909,Deric R. Mccloud,NaN,USD,2025-07-29 16:46:42.229846+00:00
882,883,1310,44265,20130722,CVC Capital Partners VI fund,NaN,EUR,2025-07-29 16:46:42.229846+00:00
979,980,1600,15300,20131107,Fund VIII,NaN,USD,2025-07-29 16:46:42.229846+00:00
1342,1343,1458,4403,20131125,Carlyle Partners VI,NaN,USD,2025-07-29 16:46:42.229846+00:00
1433,1434,1135,4248,20130513,Warburg Pincus Private Equity XI,NaN,USD,2025-07-29 16:46:42.229846+00:00

In [47]:
df_funds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1493 entries, 0 to 1492
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fund_id               1493 non-null   object
 1   object_id             1493 non-null   object
 2   name                  1493 non-null   object
 3   funded_at             1381 non-null   object
 4   raised_amount         1493 non-null   object
 5   raised_currency_code  1493 non-null   object
 6   source_url            1214 non-null   object
 7   source_description    1161 non-null   object
 8   created_at            1493 non-null   object
 9   updated_at            1493 non-null   object
dtypes: object(10)
memory usage: 116.8+ KB

In [21]:
# Set Profiling Rule
# list check data type (all columns)
data_type_column = funds_profiling.get_columns()

#list check unique values
unique_values = []

#list check percentage missing values
missing_values = ['funded_at','source_url','source_description']

#list check valid date values
valid_date = ['funded_at']

# Set Profiling rule to object
funds_profiling.selected_columns(data_type_column, unique_values, missing_values, valid_date)

In [22]:
# Create Reporting Profiling
report_funds = funds_profiling.reporting()
report_funds

{'created_at': '2025-04-06', 'report': {'fund_id': {'data_type': 'object'}, 'object_id': {'data_type': 'object'}, 'name': {'data_type': 'object'}, 'funded_at': {'data_type': 'object', 'percentage_missing_value': 7.5, 'percentage_valid_date': 92.5}, 'raised_amount': {'data_type': 'float64'}, 'raised_currency_code': {'data_type': 'object'}, 'source_url': {'data_type': 'object', 'percentage_missing_value': 18.69}, 'source_description': {'data_type': 'object', 'percentage_missing_value': 22.24}, 'created_at': {'data_type': 'datetime64[ns]'}, 'updated_at': {'data_type': 'datetime64[ns]'}}}

{'created_at': '2025-04-06',
 'report': {'fund_id': {'data_type': 'object'},
  'object_id': {'data_type': 'object'},
  'name': {'data_type': 'object'},
  'funded_at': {'data_type': 'object',
   'percentage_missing_value': 7.5,
   'percentage_valid_date': 92.5},
  'raised_amount': {'data_type': 'float64'},
  'raised_currency_code': {'data_type': 'object'},
  'source_url': {'data_type': 'object', 'percentage_missing_value': 18.69},
  'source_description': {'data_type': 'object',
   'percentage_missing_value': 22.24},
  'created_at': {'data_type': 'datetime64[ns]'},
  'updated_at': {'data_type': 'datetime64[ns]'}}}

## Profiling Data Tabel investments

In [23]:
# Profiling Table investments
df_investments = extract_database('investments')

# create profiling object
investments_profiling = Profiling(data = df_investments, table_name='investments')

# get columns from the table
investments_profiling.get_columns()

['investment_id',
 'funding_round_id',
 'funded_object_id',
 'investor_object_id',
 'created_at',
 'updated_at']

In [24]:
df_investments.iloc[:5]

,investment_id,funding_round_id,funded_object_id,investor_object_id,created_at,updated_at
0,41,27,c:34,f:127,2007-06-13 09:04:50,2013-09-06 11:20:07
1,42,27,c:34,f:67,2007-06-13 09:04:50,2013-09-06 11:20:07
2,43,28,c:34,f:127,2007-06-13 09:05:28,2013-09-06 11:20:07
3,44,28,c:34,f:67,2007-06-13 09:05:28,2013-09-06 11:20:07
4,45,29,c:27,f:17,2007-06-13 09:33:11,2008-05-20 20:43:02

In [25]:
df_investments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59407 entries, 0 to 59406
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investment_id       59407 non-null  int64
 1   funding_round_id    59407 non-null  int64
 2   funded_object_id    59407 non-null  object
 3   investor_object_id  59407 non-null  object
 4   created_at          59407 non-null  datetime64[ns]
 5   updated_at          59407 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(2), object(2)
memory usage: 2.7+ MB

In [26]:
# Set Profiling Rule
# list check data type (all columns)
data_type_column = investments_profiling.get_columns()

#list check unique values
unique_values = []

#list check percentage missing values
missing_values = []

#list check valid date values
valid_date = []

# Set Profiling rule to object
investments_profiling.selected_columns(data_type_column, unique_values, missing_values, valid_date)

In [27]:
# Create Reporting Profiling
report_investments = investments_profiling.reporting()
report_investments

{'created_at': '2025-04-06', 'report': {'investment_id': {'data_type': 'int64'}, 'funding_round_id': {'data_type': 'int64'}, 'funded_object_id': {'data_type': 'object'}, 'investor_object_id': {'data_type': 'object'}, 'created_at': {'data_type': 'datetime64[ns]'}, 'updated_at': {'data_type': 'datetime64[ns]'}}}

{'created_at': '2025-04-06',
 'report': {'investment_id': {'data_type': 'int64'},
  'funding_round_id': {'data_type': 'int64'},
  'funded_object_id': {'data_type': 'object'},
  'investor_object_id': {'data_type': 'object'},
  'created_at': {'data_type': 'datetime64[ns]'},
  'updated_at': {'data_type': 'datetime64[ns]'}}}

## Profiling Data Tabel ipos

In [53]:
# Profiling Table ipos
df_ipos = extract_database('ipos')

# create profiling object
ipos_profiling = Profiling(data = df_ipos, table_name='ipos')

# get columns from the table
ipos_profiling.get_columns()

['ipo_id',
 'object_id',
 'valuation_amount',
 'valuation_currency_code',
 'raised_amount',
 'raised_currency_code',
 'public_at',
 'stock_symbol',
 'source_url',
 'source_description',
 'created_at',
 'updated_at']

In [54]:
# Profiling Table fact_ipos
df_fact_ipos = extract_database('fact_ipos',db_name='warehouse')

# create profiling object
fact_ipos_profiling = Profiling(data = df_fact_ipos, table_name='fact_ipos')

# get columns from the table
fact_ipos_profiling.get_columns()

['ipo_id',
 'ipo_nk',
 'company_id',
 'public_at',
 'valuation_amount',
 'raised_amount',
 'valuation_currency_code',
 'raised_currency_code',
 'stock_symbol',
 'created_at']

In [55]:
df_ipos.iloc[:5]

,ipo_id,object_id,valuation_amount,valuation_currency_code,raised_amount,raised_currency_code,public_at,stock_symbol,source_url,source_description,created_at,updated_at
0,751,c:29324,0.00,USD,0.00,None,None,NYSE:SLH,None,None,2011-12-13T04:50:14.000Z,2011-12-13T04:50:14.000Z
1,1,c:1654,0.00,USD,0.00,USD,1980-12-19T00:00:00.000Z,NASDAQ:AAPL,None,None,2008-02-09T05:17:45.000Z,2012-04-12T04:02:59.000Z
2,2,c:1242,0.00,USD,0.00,None,1986-03-13T00:00:00.000Z,NASDAQ:MSFT,None,None,2008-02-09T05:25:18.000Z,2010-12-11T12:39:46.000Z
3,3,c:342,0.00,USD,0.00,None,1969-06-09T00:00:00.000Z,NYSE:DIS,None,None,2008-02-09T05:40:32.000Z,2010-12-23T08:58:16.000Z
4,4,c:59,0.00,USD,0.00,None,2004-08-25T00:00:00.000Z,NASDAQ:GOOG,None,None,2008-02-10T22:51:24.000Z,2011-08-01T20:47:08.000Z

In [57]:
df_fact_ipos.iloc[:5]

,ipo_id,ipo_nk,company_id,public_at,valuation_amount,raised_amount,valuation_currency_code,raised_currency_code,stock_symbol,created_at
0,1,147,601,21000101,0.0,0.0,USD,None,NASDAQ:NWS,2025-07-29 16:48:35.515728+00:00
1,2,191,16749,20090814,648000000.0,0.0,USD,USD,NASDAQ:AVGO,2025-07-29 16:48:35.515728+00:00
2,3,420,42145,21000101,0.0,0.0,USD,None,GTSM:4147,2025-07-29 16:48:35.515728+00:00
3,4,567,13750,21000101,0.0,0.0,USD,None,NYSE:PLT,2025-07-29 16:48:35.515728+00:00
4,5,782,40478,20120323,86250000.0,0.0,USD,USD,NASDAQ:TSRO,2025-07-29 16:48:35.515728+00:00

In [58]:
df_ipos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1194 entries, 0 to 1193
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ipo_id                   1194 non-null   object
 1   object_id                1194 non-null   object
 2   valuation_amount         1194 non-null   object
 3   valuation_currency_code  1192 non-null   object
 4   raised_amount            1194 non-null   object
 5   raised_currency_code     662 non-null    object
 6   public_at                623 non-null    object
 7   stock_symbol             1194 non-null   object
 8   source_url               178 non-null    object
 9   source_description       168 non-null    object
 10  created_at               1194 non-null   object
 11  updated_at               1194 non-null   object
dtypes: object(12)
memory usage: 112.1+ KB

In [59]:
df_fact_ipos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1194 entries, 0 to 1193
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ipo_id                   1194 non-null   int64
 1   ipo_nk                   1194 non-null   int64
 2   company_id               1194 non-null   int64
 3   public_at                1194 non-null   int64
 4   valuation_amount         1187 non-null   float64
 5   raised_amount            1192 non-null   float64
 6   valuation_currency_code  1192 non-null   object
 7   raised_currency_code     662 non-null    object
 8   stock_symbol             1194 non-null   object
 9   created_at               1194 non-null   datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(2), int64(4), object(3)
memory usage: 93.4+ KB

In [61]:
df_ipos[df_ipos['ipo_id']=='37']

,ipo_id,object_id,valuation_amount,valuation_currency_code,raised_amount,raised_currency_code,public_at,stock_symbol,source_url,source_description,created_at,updated_at
34,37,c:3657,11000000000.00,USD,0.00,None,None,HK700,None,None,2008-05-14T23:46:19.000Z,2008-05-15T19:30:23.000Z

In [60]:
df_fact_ipos[df_fact_ipos['valuation_amount'].isna()]

,ipo_id,ipo_nk,company_id,public_at,valuation_amount,raised_amount,valuation_currency_code,raised_currency_code,stock_symbol,created_at
29,30,37,2507,21000101,NaN,0.000000e+00,USD,None,HK700,2025-07-29 16:48:35.515728+00:00
40,41,847,9353,20120518,NaN,NaN,USD,USD,NASDAQ:FB,2025-07-29 16:48:35.515728+00:00
105,106,746,9886,20111107,NaN,0.000000e+00,USD,USD,NASDAQ:GRPN,2025-07-29 16:48:35.515728+00:00
207,208,78,10376,20081217,NaN,0.000000e+00,JPY,None,3632,2025-07-29 16:48:35.515728+00:00
538,539,48,3102,19980401,NaN,0.000000e+00,USD,None,LVLT,2025-07-29 16:48:35.515728+00:00
554,555,1310,248,20131107,NaN,1.820000e+09,USD,USD,NYSE:TWTR,2025-07-29 16:48:35.515728+00:00
997,998,5,526,19970501,NaN,0.000000e+00,USD,None,NASDAQ:AMZN,2025-07-29 16:48:35.515728+00:00

In [31]:
# Set Profiling Rule
# list check data type (all columns)
data_type_column = ipos_profiling.get_columns()

#list check unique values
unique_values = ['valuation_currency_code','raised_currency_code']

#list check percentage missing values
missing_values = ['valuation_currency_code','raised_currency_code',
                  'public_at','source_url','source_description']

#list check valid date values
valid_date = ['public_at']

# Set Profiling rule to object
ipos_profiling.selected_columns(data_type_column, unique_values, missing_values, valid_date)

In [32]:
# Create Reporting Profiling
report_ipos = ipos_profiling.reporting()
report_ipos

{'created_at': '2025-04-06', 'report': {'ipo_id': {'data_type': 'object'}, 'object_id': {'data_type': 'object'}, 'valuation_amount': {'data_type': 'float64'}, 'valuation_currency_code': {'data_type': 'object', 'unique_value': ['USD', 'JPY', nan, 'CAD', 'GBP'], 'percentage_missing_value': 0.17}, 'raised_amount': {'data_type': 'float64'}, 'raised_currency_code': {'data_type': 'object', 'unique_value': ['USD', nan, 'EUR', 'JPY', 'GBP', 'CAD'], 'percentage_missing_value': 44.56}, 'public_at': {'data_type': 'datetime64[ns]', 'percentage_missing_value': 47.82, 'percentage_valid_date': 52.18}, 'stock_symbol': {'data_type': 'object'}, 'source_url': {'data_type': 'object', 'percentage_missing_value': 85.09}, 'source_description': {'data_type': 'object', 'percentage_missing_value': 85.93}, 'created_at': {'data_type': 'datetime64[ns]'}, 'updated_at': {'data_type': 'datetime64[ns]'}}}

{'created_at': '2025-04-06',
 'report': {'ipo_id': {'data_type': 'object'},
  'object_id': {'data_type': 'object'},
  'valuation_amount': {'data_type': 'float64'},
  'valuation_currency_code': {'data_type': 'object',
   'unique_value': ['USD', 'JPY', nan, 'CAD', 'GBP'],
   'percentage_missing_value': 0.17},
  'raised_amount': {'data_type': 'float64'},
  'raised_currency_code': {'data_type': 'object',
   'unique_value': ['USD', nan, 'EUR', 'JPY', 'GBP', 'CAD'],
   'percentage_missing_value': 44.56},
  'public_at': {'data_type': 'datetime64[ns]',
   'percentage_missing_value': 47.82,
   'percentage_valid_date': 52.18},
  'stock_symbol': {'data_type': 'object'},
  'source_url': {'data_type': 'object', 'percentage_missing_value': 85.09},
  'source_description': {'data_type': 'object',
   'percentage_missing_value': 85.93},
  'created_at': {'data_type': 'datetime64[ns]'},
  'updated_at': {'data_type': 'datetime64[ns]'}}}

#

# Spreadsheet

## Profiling Data People

In [65]:
# Profiling Table people
df_people = extract_database('people')

# create profiling object
people_profiling = Profiling(data = df_people, table_name='people')

# get columns from the table
people_profiling.get_columns()

['affiliation_name',
 'birthplace',
 'first_name',
 'last_name',
 'object_id',
 'people_id']

In [67]:
# Profiling Table dim_people
df_dim_people = extract_database('dim_people',db_name='warehouse')

# create profiling object
dim_people_profiling = Profiling(data = df_dim_people, table_name='dim_people')

# get columns from the table
dim_people_profiling.get_columns()

['people_id',
 'people_nk',
 'full_name',
 'first_name',
 'last_name',
 'affiliation',
 'birthplace',
 'created_at']

In [68]:
df_people.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226709 entries, 0 to 226708
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   affiliation_name  226691 non-null  object
 1   birthplace        28084 non-null   object
 2   first_name        226704 non-null  object
 3   last_name         226708 non-null  object
 4   object_id         226709 non-null  object
 5   people_id         226709 non-null  object
dtypes: object(6)
memory usage: 10.4+ MB

In [69]:
df_dim_people.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226709 entries, 0 to 226708
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   people_id    226709 non-null  int64
 1   people_nk    226709 non-null  object
 2   full_name    226708 non-null  object
 3   first_name   226704 non-null  object
 4   last_name    226708 non-null  object
 5   affiliation  226691 non-null  object
 6   birthplace   28084 non-null   object
 7   created_at   226709 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), int64(1), object(6)
memory usage: 13.8+ MB

In [35]:
# create profiling object
people_profiling = Profiling(data = df_people, table_name='people')

In [36]:
# get columns from the table
people_profiling.get_columns()

['people_id',
 'object_id',
 'first_name',
 'last_name',
 'birthplace',
 'affiliation_name']

In [37]:
# Set Profiling Rule
# list check data type (all columns)
data_type_column = people_profiling.get_columns()

#list check unique values
unique_values_column = ['birthplace']

#list check percentage missing values
missing_values_column = ['first_name','last_name','birthplace','affiliation_name']

#list check valid date values
valid_date_column = []

# Set Profiling rule to object
people_profiling.selected_columns(data_type_column, unique_values_column, missing_values_column, valid_date_column)

In [ ]:
# Create Reporting Profiling
report_people = people_profiling.reporting()
report_people

{'created_at': '2025-04-06', 'report': {'people_id': {'data_type': 'object'}, 'object_id': {'data_type': 'object'}, 'first_name': {'data_type': 'object', 'percentage_missing_value': 0.0}, 'last_name': {'data_type': 'object', 'percentage_missing_value': 0.0}, 'birthplace': {'data_type': 'object', 'unique_value': [nan, 'Redding, CA', 'Detroit, MI', 'Gainesville, FL', 'Hickery, North Carolina', 'Surrey, England', 'USA', 'St. Louis, MO', 'Israel', 'New York, New York', 'Copenhagen, Denmark', 'Kyoto, Japan', 'Orlando, Florida', 'Great Neck, New York', 'Wisconsin', 'Cedar Falls, Iowa', 'Pennsylvania', 'Taipei, Taiwan', 'Brooklyn, NY', 'Santa Monica, CA', 'Haifa, Israel', 'California', 'Pittsburgh, PA', 'Palo Alto CA', 'Paris, France', 'Queens, NY', 'Koblenz, Germany', 'Switzerland', 'New York, NY', 'New Delhi, India', 'Helsinki, Finland', 'San Diego, CA', 'Delft', 'OHIO', 'Belfast, Northern Ireland', 'Dhaka, bangladesh', 'Braunschweig, Germany', 'Wayne, New Jersey', 'Kyiv, Ukraine', 'Bethlehem, PA', 'Santa Rosa, CA', 'Boston', 'Columbus, OH', 'New York', 'Indianapolis, IN USA', 'Minneapolis', 'Tours, France', 'Minneapolis, Minn', 'Menomenee Falls, WI', 'Santa Monica CA', 'Chennai (Tamil Nadu, India)', 'Boston, MA', 'Santa Cruz, CA', 'Stanford, CA', 'Tampa, FL', 'Fairbanks, Alaska', 'Istanbul, Turkey', 'Los Angeles', 'Scarborough, N Yorkshire, UK', 'San Francisco, CA', 'Rome, Italy', 'London', 'Appleton, WI', 'Chicago, IL', 'West Virginia', 'Jammu, India', 'Las Vegas', 'Seoul, Korea', 'Hopatacong, NJ', 'France', 'Wollongong, Australia', 'Liverpool, UK', 'Milan, Italy', 'Rimini, Italy', 'Cambridge', 'Huntington Beach, California', 'Washington, DC', 'The Hague', 'Netherlands', 'london', 'England, UK', 'Westwood, NJ', 'New Jersey', 'Bromma, Stockholm', 'Huntsville, Alabama', 'England', 'Brasi\xadlia, DF, Brasil', 'Estonia', 'Tartu, Estonia', 'Denmark', 'Sydney, Australia', 'Prague', 'US', 'Philadelphia', 'Morristown, NJ', 'San Francisco, California, USA', 'Deland, FL', 'Modesto, CA', 'Portland, OR', 'Russellville, Ky', 'California, USA', 'New Britain, CT', 'Sofia', 'Varberg, Sweden', 'Kuwait', 'worcester, ma', 'Mt. Lebanon, PA', 'New Delhi', 'Neuilly sur Seine', 'New York City', 'Albuquerque, New Mexico, USA', 'Smithtown, New York', 'Pasadena, CA', 'Minneapolis, MN', 'Brockton, MA', 'Santa Monica, California', 'Hollywood, CA', 'Canada', 'Sao Paulo, Brazil', 'Anchorage, Alaska', 'Springfield, IL', 'Glasgow, Scotland', 'South Africa', 'Centralia, Washington, USA', 'piranshahr-iran', 'Media, PA', 'London, UK', 'Beverly Hills', 'Texas', 'Pittsburgh', 'yonkers', 'NY', 'New Rochelle, New York', 'Abington, PA', 'Indiana', 'Auckland, New Zealand', 'Portsmouth', 'Toronto', 'Virginia, USA', 'Cork, Ireland', 'Kobe, Japan', 'Chicago', 'Johannesburg, South Africa', 'South Korea', 'Alfred, Maine', 'Glendora, CA', 'UK', 'Taiwan', 'Miami, FL', 'Copenhagen', 'Cologne, Germany', 'Washington DC', 'Nashua, NH', 'Metairie, LA', 'Charlottesville, VA', 'Los Angeles, CA', 'State College, PA', 'Baltimore, MD', 'Phoenix', 'Durham NC', 'Toulouse, France', 'Tarzana, CA', 'London England', 'Wahoo, NE', 'Bombay, India', 'NYC', 'Arlington, Virginia, USA', 'Boston MA USA', 'Chicago, Illinois', 'Windsor Nova Scotia, Canada', 'c', 'Spain', 'San Jose, Costa Rica', 'Kingston, Jamaica', 'Blackpool', 'newplace', 'Poland', 'Houston, Texas', 'Cambridge, Mass.', 'Buenos Aires, Argentina', 'Comodoro Rivadavia, Chubut, Argentina', 'Lutherville-Timonium, Maryland, USA', 'Hobart, Tasmania', 'Limoges, France', 'Espoo, Finland', 'Longview, WA', 'Cleveland Heights, Ohio', 'San Luis Obispo, California, USA', 'Michigan, USA', 'Berlin', 'Stuttgart, Germany', 'Concord, MA', 'Tarn Taran, India', 'Fairhope, AL', 'Allentown PA', 'Honolulu HA', 'Kiev, Ukraine', 'The Hague, Netherlands', 'Mississauga, Canada', 'Valence, France', 'Hyderabad, India', 'Des Moines, IA', 'Tonasket, WA', 'Easton, PA', 'israel', 'Slough', 'VA', 'Albany, New York', 'Florida', 'Sweden', 'Sudbury, Ontario, Canada', 'Tallinn, Estonia', 'White Plains, NY', 'london, england', 'Barcelona', 'India', 'Newport Beach, CA', 'Jerusalem', 'Iowa', 'Islamabad', 'Moscow', 'Kansas City, MO', 'Brazil', 'San Luis Obispo, CA', 'Belgium', 'Montreal', 'Berwick, PA', 'Argentina', 'Schenectady, NY', 'Kansas City, Missouri', 'Uddevalla, Sweden', 'Ramat Gan, Israel', 'Jerusalem, Israel', 'San Francisco', 'Germany', 'Amityville, NY', 'Hamburg', 'Dublin, Ireland', 'Washington, D.C.', 'Singapore', 'Oklahoma City', 'Phoenix, AZ', 'Amritsar', 'Odessa, TX', 'Portugal', 'Kentucky', 'Brisbane, Australia', 'Honolulu, Hawaii', 'Swidnica', 'North Carolina', 'Seattle', 'CT', 'Petersburg, IL', 'Amherst, NY', 'Massachusetts', 'Lexington, KY', 'Melbourne, Australia', 'Fresno, CA', 'Youngstown, Ohio', 'Tampa, FL, USA', 'Illinois', 'Greeley, CO', 'Bekasi', 'Maryland', 'San Jose, CA', 'Falmouth, ME', 'Osaka, Japan', 'Austria', 'Munich', 'Southern California', 'River Forest, IL', 'Bilaspur', 'Zurich', 'Cape Town, South Africa', 'Colorado', 'Ghent, Belgium', 'CT, USA', 'Philadelphia, PA, USA', 'Lake Forest, CA', 'Dallas, TX', 'China', 'Pueblo, Co', 'Austin, Texas', 'Kharkov, Ukraine', 'Rehovot, Israel', 'Banaglore', 'Brooklyn, New York', 'palmerston Ontario canade', 'Seattle, WA', 'Lund, Sweden', 'Newark, NJ', 'Ireland', 'Toledo, Ohio USA', 'United Kingdom', 'Berkeley, CA', 'Ukraine', 'Narragansett, RI', 'Lake Wales, FL', 'Moscow, Russia', 'Davis, CA', 'Norway', 'Seattle, Washington', 'Portsmouth, NH', 'Michigan', 'Lyndhurst, UK', 'Vienna, Austria', 'Rouen', 'Turkey', 'Brighton, England', 'Omaha, Nebraska, USA', 'Huntington, NY', 'Palo Alto, CA', 'Ann Arbor, Michigan', 'PA', 'Reading, Berkshire, UK', 'Oxford', 'Perth, Australia', 'Akron, OH', 'Malaysia', 'Hammond, LA', 'Manchester, New Hampshire', 'Kauniainen, Finland', 'Allentown, PA', 'Sydney', 'Detroit', 'Vancouver', 'Avigliana, Italy', 'Tel-Aviv', 'Lewiston', 'Morristown, New Jersey, United States', 'Ann Arbor, Michigan, USA', 'Baltimore', 'Tvedestrand, Norway', 'Washington', 'Vancouver, Washington', 'Ceres, South Africa', 'Minsk, Belarus', 'Truckee, CA', 'St. Charles, IL', 'Houston, TX', 'Tehran', 'Chicago, Ill', 'LA', 'Paris', 'Craiova', 'Ukriane', 'Eindhoven', 'Bronx, NY', 'Guadalajara, Mexico', 'Ridgewood,NJ', 'Bastia, France', 'Junction City, KS', 'Zimbabwe', 'New Zealand', 'Stockholm, Sweden', 'Park Ridge, IL', 'Taipei', 'Gujarat, India', 'Iran, Tehran', 'Napa, CA', 'Pakistan', 'Edmonton, Alberta', 'Salinas, CA', 'Australia', 'Madrid', 'Orange County, CA', 'Delhi', 'Jacksonville, FL', 'Milwaukee, WI', 'Utah', 'Troy, MI', 'Bremen, Germany', 'Biratnagar, Nepal', 'Coimbra, Portugal', 'Karl-Marx-Stadt, Germany', 'Siegen', 'Jericho, NY', 'Montreal, Quebec, Canada', 'Tehran, Iran', 'Beijing, China', 'London, England', 'MalmÃ¶, Sweden', 'Philadelphia Pa', 'Buffalo, NY', 'MA', 'East Meadow, NY', 'Helena, Montana', 'Korea', 'Huáº¿, Viá»\x87t-Nam', 'Hillsdale, NJ', 'Omaha, NE', 'ljubljana, slovenia', 'Woonsocket, RI', 'San Antonio, TX', 'Leningrad, USSR', 'Nice, France', 'Brussels', 'shanghai', 'Santiago, Chile', 'Philadelphia, PA', 'Tullamore, IE', 'Brno, Czech Republic', 'Ashford, Kent, UK', 'Wellington, New Zealand', 'Edmonton, AB', 'Goshen, IN', 'Plano, Texas, USA', 'Atlanta, Georgia', 'Stockholm', 'Vienna', 'Atlanta, GA', 'Columbus, GA', 'Lachine, Canada', 'Boca Raton, FL', 'Dublin', 'Northampton', 'Bucharest', 'Des Moines, Iowa', 'Hong Kong', 'New Bedford, MA', 'Portsmouth, UK', 'Glen Cove, New York', 'Watertown, CT', 'Bethesda', 'Cannon Falls, MN', 'Milwaukee, Wisconsin', 'Connecticut', 'Minnesota', 'Cleveland', 'Dordrecht', 'Johannesburg', 'Edinburgh', 'The Netherlands', 'Scotland', 'Princeton, NJ', 'berkeley', 'Tianjin, China', 'Surrey, UK', 'Birmingham, UK', 'Grammichele (CT) Italia', 'Yerevan, Armenia', 'Bratislava, Slovakia', 'Lancashire, UK', 'Urbana', 'Phoenix Arizona', 'Memphis, TN', 'Winnipeg, Canada', 'Somerville, Mass.', 'Hamilton, Canada', 'Meriden Connecticut', 'Istanbul', 'Karachi,Pakisatn', 'Pensacola, FL', 'Cleveland, Ohio', 'Kinshasa', 'Rio Grande, Brazil', 'United States', 'Kennebunkport, Maine', 'City of New York', 'Tokyo', 'Chennai, India', 'birmingham', 'Rochester, MN', 'Rochester, NY', 'Quebec, Canada', 'Anaheim, CA, USA', 'Evanston, IL', 'Novosibirsk, Russia', 'South Carolina', 'Toronto, Canada', 'Burlington, VT', 'Virginia', 'knoxville', 'Rockville, Maryland', 'Bellflower, CA', 'Lisboa, Portugal', 'Boise, ID', 'Melrose, MA', 'Lille', 'Neptune, New Jersey, USA', 'Barberton, Ohio', 'Patna', 'Boise ID', 'Charleston, SC', 'Barcelona, Spain', 'Bonn, Germany', 'Munich, Germany', 'Edmonton, Canada', 'Hemet, California', 'Langenfeld', 'Northridge, California', 'Sherman Oaks, CA', 'Orange, CA', 'Newton MA', 'Louisville, KY', 'Nashville, TN', 'Sligo, Ireland', 'Poznan, Poland', 'Liverpool', 'Boston, Mass.', 'Pico Rivera, California', 'Ede, The Netherlands', 'Slovakia', 'Bangalore, India', 'South Bend, Indiana, USA', 'Athens, Greece', 'Amsterdam, The Netherlands', 'rajasthan, india', 'Karlsruhe', 'Lowell, MA', 'Pachmari, Madhya Pradesh, India', 'Sacramento, CA', 'Peoria, IL', 'Canberra', 'Wales', 'Maine', 'Chennai', 'Idaho Falls ID', 'Los Angeles, California', 'Tampa Bay,FL', 'New York City, New York, USA', 'Marathon, FL', 'Belleville, Ontario, Canada', 'San Jose', 'Los Altos', 'Tramore, Co. Waterford, Ireland', 'Ann Arbor, MI', 'Atlanta', 'Norwalk, CT', 'Harbor City, CA', 'Greenville, NC', 'Vancouver, Canada', 'Augusta, GA', 'Toronto, Ontario', 'Kapuskasing, Ontario, Canada', 'Frankfurt', 'Asse, Belgium', 'Halifax, UK', 'Austin, TX', 'Santa Clara, CA', 'Harrogate, UK', 'Bergen, Norway', 'Antwerp', 'Otaniemi, Finland', 'INDIA', 'Bayport, NY', 'Ohio', 'Manhattan Beach, CA', 'Japan', 'Tacoma, WA', 'Illinois, USA', 'Manilla', 'Vineland, NJ', 'Janesville, WI', 'Hamburg, Germany', 'Pune, India', 'Uruguay', 'Boston, Massachusetts', 'Oahu, HI', 'Calgary, Alberta, Canada', 'Boston, USA', 'Bonn', 'Eugene, OR', 'Kanhangad', 'Nova Scotia', 'El Paso, TX', 'Madrid, Spain', 'Essen', 'Youngstown', 'Tacoma', 'Turnhout, Belgium', 'Carbondale, PA', 'Perth, Western Australia', 'Havre de Grace, Maryland, USA', 'Torrance, California, USA', 'Peru, IN', 'Langerak', 'Miami, Florida', 'Vietnam', 'Fort Wayne, IN', 'Canton', 'Toledo, Ohio', 'Dearborn, MI', 'Ohio, USA', 'Pennsylvania, USA', 'Capital Federal | Buenos Aires | Argentina', 'Novi Sad', 'Giubiasco, Switzerland', 'Finland', 'Geneva, Switzerland', 'Warendorf, germany', 'Cologne', 'Moline, IL', 'Tulsa, Oklahoma', 'Prince George, BC, Canada', 'Leeuwarden, The Netherlands', 'Fort Belvoir, VA', 'Anderson, IN', 'Gosford', 'North Vancouver', 'Oakland, Ca', 'Jaffna, Sri Lanka', 'Honolulu, HI', 'Bangladesh', 'Bellevue, Washington', 'Leicester, England', 'Rome - Italy', 'Windsor, Ontario', 'NYC, NY', 'Belfast', 'Whitefish Bay, WI', 'Manchester', 'Worcester,MA', 'Edmonton', 'Douglas, Isle of Man, UK', 'Dnepropetrovsk, Ukraine', 'Miami', 'Newnan, Georgia', 'Mumbai', 'Oxford, UK', 'Amsterdam', 'Nagpur', 'Bilbao, Spain', 'Karachi', 'maryland', 'Cochin', 'Galway, Ireland', 'Mississauga, Ontario', 'Graz', 'Dallas', 'Charlotte, NC', 'Braga, Portugal', 'Sylhet, Bangladesh', 'Versailles, OH', 'Vancouver, BC, Canada', 'Jamaica', 'Alcoy', 'Salt Lake City, Utah', 'rio de janeiro', 'Livingston, NJ', 'Brasil', 'Konstanz, Germany', 'Malmo, Sweden', 'Marseille, France', 'Mpls, MN', 'Pisa, Italy', 'Buenos Aires', 'Tanjay City, Negros Oriental Philippines', 'Maldives', 'Beirut, Lebanon', 'Lisbon, Portugal', 'Somerset, Massachusetts', 'Cagliari', 'Kerala,India', 'Calicut', 'kasaragod', 'Zaria, Nigeria', 'Kazan, Russia', 'Pekin, IL', 'Denver,  CO USA', 'Augsburg, Germany', 'DAHANU, THANE, MAHARASHTRA, INDIA', 'Nellore', 'amsterdam', 'Adelaide, Australia', 'Kelheim', 'Tel Aviv', 'Meerut', 'San Diego', 'Vienna, VA', 'Edinburgh, Scotland', 'Laport Ind', 'Busan', 'Denville, NJ', 'Chester, UK', 'Bakersfield, California', 'shihua', 'Ashland, OR', 'Assisi, Italy', 'Jakarta, Indonesia', 'Bochum', 'Oberhausen', 'Falmouth, MA', 'Massapequa, NY', 'Georgia, USA', 'Iron Mountain, MI', 'Da Nang, Vietnam', 'Guangdong, China', 'Naples', 'MD, USA', 'Uppsala', 'Romania', 'Manila, Philippines', 'Rio de Janeiro, Brazil', 'Kansas City', 'Norwood,New Jersey', 'bali', 'Madison Wisconsin', 'ISRAEL', 'Tashkent, Uzbekistan', 'Rotterdam', 'East Islip, NY', 'Bucharest, Romania', 'Napoli, Italy', 'Reykjavik, Iceland', 'Gdynia, Poland', 'St. Louis', 'Newton, Mass', 'Stamford, CT', 'Cleveland, Ohio, USA', 'Ontario, Canada', 'St. Gallen, Switzerland', 'Newcastle-upon-Tyne', 'Washington D.C.', 'Beverly Hills, CA', 'Milwaukee', 'Jamestown, RI', 'Timisoara/Romania', 'Brisbane', 'Emmen, the Netherlands', 'Saint Joseph, Missouri', 'Arad, Romania', 'Sedona, AZ', 'New Hampshire', 'Kelowna', 'Lebanon', 'Dhahran, Saudi Arabia', 'CA', 'Morocco', 'Misawa, Japan', 'Cairo, Egypt', 'Dallas, Texas', 'Harrow, London', 'Suffern, NY', 'McLean, VA', 'La Honda, California', 'Grenoble', 'San Anselmo, CA', 'Saint Charles, IL', 'Hyderadab', 'Tacoma, Washington', 'Basel', 'Freiburg, Germany', 'Beaumont, Texas', 'adoni', 'Guines, Cuba', 'Seattle Washington, USA', 'mysoor', 'Milan', 'New Orleans', 'Kamakura, Japan', 'Willingboro, NJ', 'Ottawa, Canada', 'Patan, Gujarat, India', 'Teofilo Otoni, MG, Brazil', 'Caldwell, Idaho', 'Royal Oak, MI', 'Fairmont, WV', 'Queens, New York', 'Vallejo, CA', 'U.S.', 'Norwood, MA', 'Tosu, Japan', 'Colne', 'Paradise, CA', 'Renton, Washington', 'Manhattan', 'Eygpt', 'Amman - Jordan', 'Italy', 'lodo', 'Monongahela, PA', 'Russia', 'DeKalb, IL', 'Goa', 'Strasbourg, France', 'Oneonta, NY', 'Saint Louis , MO', 'montreal, quebec', 'Grand Rapids, MI', 'Hampton, VA', 'Liverpool, The UK', 'Osaka', 'Kochi', 'Hawaii', 'Gothenburg, Sweden', 'Neyveli', 'Frankston', 'Rosario', 'Winnipeg', 'Constance, Germany', 'Glen Cove, NY', 'Long Beach, CA', 'Bowling Green, OH', 'Amsterdam, the Netherlands', 'Eskisehir, Turkey', 'Chipping Norton, UK', 'Gainesville, Florida', 'Irvine, Scotland', 'American Fork, Utah', 'Hyderabad', 'Rio de Janeiro - RJ - Brazil', 'Newport Beach', 'Saratoga, CA', 'Princeton, MA', 'Portchester, NY', 'Lexington, SC', 'Los Altos, CA', 'Chapel Hill, NC', 'Aberdeen, Scotland', 'San Remo - Italy', 'Syracuse, NY', 'Lyon, France', 'Bangalore', 'Orlando, FL', 'Thiruvananthapuram', 'Amersfoort, The netherlands', 'Brighton UK', 'Atlanta, GA USA', 'Turku, Finland', 'Staten Island, New York', 'Pathankot', 'Chandigarh', 'Portsmouth, England', 'chicago', 'Nicaragua', 'Madurai', 'Fort Wayne, Indiana, USA', 'Montreal, Canada', 'Melbourne', 'Denver, CO', 'Jupiter, FL', 'Bogota, Colombia', 'East Hampton, NY', 'Guwahati', 'Cleveland, OH', 'Amman', 'Cleburne Texas', 'Saarlouis, Germany', 'Maine, USA', 'Azerbaijan, Baku', 'Wellington', 'Bern', 'Puri, Orissa, India', 'Madera, CA', 'The Office, CA', 'Tokyo, Japan', 'Sacramento,CA', 'Carlow', 'Grenoble, France', 'Gloucester', 'Leuven', 'Ozora', 'Chicago IL', 'Harrisburg, PA', 'Benoni', 'Bradford, UK', 'Kymmerer, Wyoming', 'BogotÃ¡, Colombia', 'Verona', 'Mysore', 'Robbinsdale, MN', 'Portland Maine', 'Veliko Tarnovo, Bulgaria', 'Chile', 'Prince Edward Island', 'Leipzig, Germany', 'Marion, VA', 'Kent', 'Ndola, Zambia', 'NynÃ¤shamn, Sweden', 'Rome, italy', 'Torino', 'Brzesko', 'Northern Ireland', 'Bern, Switzerland', 'Leuven, Belgium', 'Indianapolis', 'Portland Oregon', 'Palo Alto', 'Van Nuys, CA', 'Neuss', 'Skopje', 'Torino, Italy', 'Colorado Springs, CO', 'Kirsehir, Turkey', 'Nottingham, England', 'St. Anthony, Idaho', 'Corvallis, OR', 'Kuala Lumpur, Malaysia', 'Bishkek', 'Cork,Ireland', 'Pasadena', 'Grand Rapids, MI, United States', 'Worcester, MA', 'Harlem USA', 'Thunder Bay', 'Bellingham, Wa', 'Cuba', 'North America', 'Varanasi, India', 'Russia, Rostov-on-Don', 'Siberia, Russia', 'Bristol, United Kingdom', 'Natal Brasil', 'Lithuania', 'MatarÃ³ (Barcelona)', 'Passaic, NJ', 'Yamuna Nagar, Haryana', 'Ft. Dix, New Jersey, USA', 'Oklahoma City, OK', 'Geelong, Australia', 'Houston, TX, US', 'Ladysmith, South Africa', 'Duesseldorf', 'Indio, CA', 'Karachi, Pakistan', 'Bay Area', 'Warren, Ohio, USA', 'Patna, India', 'Cape Town', 'san jose,ca', 'Oakland, CA', 'Salon de Provence', 'Bristol', 'sion', 'new york city', 'South Pasadena, CA', 'Mangalore', 'Belfast, NI', 'istanbul', 'Hibbing, Minnesota, USA', 'San Mateo, CA', 'Columbia, MD', 'Chilliwack, BC', 'Nouakchott', 'Flensburg', 'Pendaiya, Cyprus', 'Preston, England', 'Clemson, South Carolina', 'Jordan', 'Jeddah, KSA', 'Cedar Rapids, IA', 'Kaiserslautern, Germany', 'Neuwied', 'Mumbai, India', 'Glen Burnie, MD', 'Varese', 'Hamilton, New Zealand', 'Kuala Lumpur', 'Rennes, France', 'Calcutta, India', 'Ann Arbor Michigan', 'Lynchburg, VA', 'Subic Bay, Olongapo, Philippines', 'Pasadena, Ca', 'VELLORE', 'West Islip, NY', 'Redwood City, CA', 'Charleroi', 'Roma', 'Los Gatos, CA', 'Tallinn', 'Hanford, CA', 'Mt Vernon, Washington', 'Royal Leamington Spa, UK', 'Brighton', 'PÃ©cs', 'Geneva', 'AP, India', 'Thrissur', 'Azerbaijan', 'Andenes', 'Athens/ Greece', 'Chicago, Il.', 'Woodale, IL', 'Turkey / Mersin', 'Kingston, Ontario Canada', 'Empoli', 'Whittier', 'Norfolk, VA', 'Mexico City', 'OH', 'Los Angeles, CA, United States', 'Ottawa', 'Long Island, NY', 'Caracas Venezuela', 'Brookline, MA', 'Madras', 'Helsinki', 'Niagara Falls, New York, USA', 'Albany, NY', 'StenlÃ¸se', 'New York City, NY', 'New London, Connecticut', 'Hinsdale IL', 'Atlantic City, NJ', 'Avignon (France)', 'Zagreb, Croatia', 'Helsingborg, Sweden', 'Nantes, France', 'Montclair, NJ', 'Redwood City', 'Ried', 'Leiden', 'Ipswich', 'Concord, NH', 'Ostrowiec Å\x9aw., Poland', 'Tel-Aviv, Israel', 'Hungary', "L'Hay-les-Roses (France)", 'Boston, Massachusetts, USA', 'Durban, South Africa', 'san antonio', 'Weinheim / Germany', 'CsÃ\xadkszereda, Romania', 'York, NE', 'Uppsala, Sweden', 'Fairfax, Virginia', 'Englewood NJ', 'Spokane, WA', 'Delhi, India', 'Palermo, Italy', 'Georgia', 'Luebeck, Germany', 'Bursa/Turkey', 'Reykjavik', 'Europe', 'Midland, Tx.', 'Jaunpur, UP', 'Lahore', 'Oklahoma', 'Kolkata', 'Marin County, CA', 'Jawa barat', 'Goiania, Brazil', 'Manila', 'Mauritius', 'St. Johnsbury, VT', 'Mooresville, NC', 'Seattle, WA.', 'Winter Haven, FL', 'Tulcea Romania', 'Atlanta, USA', 'Galle', 'Cincinnati, OH', 'Haverhill, MA', 'Rome', 'Windsor', 'Calif', 'Apeldoorn', 'sicily', 'Orem, UT USA', 'Harbin, China', 'Alexandria VA', 'Troy, Michigan, USA', 'Trivandrum', 'Blacksburg, VA', 'Fall River, MA', 'Jakarta', 'Porterville', 'Oshimwaku, Namibia', 'Sarcelles', 'Drancy', 'USSR', 'Cambridge, Massachusetts USA', 'Kelowna, BC', 'Chelmsford', 'Bronx, N.Y.', 'Edison, NJ', 'chennai', 'Kilkenny, Ireland', 'cairo', 'United States of America', 'Belgrade, Serbia', 'Dunedin', 'Seminole, Florida, US', 'Casper, Wyoming USA', 'Alnwick, Northumberland, England', 'Montana', 'Mexico', 'Bulgaria', 'durham, NC', 'St. Ingbert', 'Gloucestershire', 'Thomaston, CT', 'Kansas City- Johnson County', 'U.S.A.', 'Racine, WI', 'Piatra Neamt, Romania', 'Houston, TX USA', '1979', 'Wausau, WI', 'Oregon', 'Mobile, AL', 'Belarussia', 'Pittsburgh, PA, USA', 'WA, Australia', 'Winona, Minnesota', 'Avignon', 'Fontainebleau, France', 'Extremadura (Spain)', 'Ft Myers, Florida', 'Norfolk, Nebraska', 'Portsmouth, VA', 'Richmond, Va', 'Iceland', 'Arcadia, California', 'Puerto Rico', 'St. Petersburg, Florida', 'belgium', 'NJ', 'Dix Hills, NY', 'Richardson, TX', 'Augsburg', 'Seoul, South Korea', 'Kanpur, India', 'Daytona Beach, FL', 'Pondicherry', 'Kathmandu, Nepal', 'Bhusawal,Maharashtra,India', 'Turkey, Istanbul', 'Tarzana, California', 'Charleston', 'Monticello, Indiana', 'New Bern, NC', 'Quebec', 'Rivas, Nicaragua', 'Sausalito, CA', 'Sucina (MURCIA)', 'Antigonish, NS', 'Sevilla', 'Scarborough, UK', 'Hyderabad, AP', 'Santa Cruz, CA.', 'Russia, Perm', 'Chicago, Il', 'Fort Collins, CO', 'Budapest, Hungary', 'Bossier', 'Copenhagen, Denmark.', 'Hereford, UK', 'Kitimat BC', 'Weymouth', 'Salto, Uruguay', 'New Delhi (INDIA)', 'Boise Idaho', 'Chester County, PA', 'Dresden | Germany', 'Ghana', 'Timaru, New Zealand', 'Denizli,Turkey', 'Malaga (Spa

{'created_at': '2025-04-06',
 'report': {'people_id': {'data_type': 'object'},
  'object_id': {'data_type': 'object'},
  'first_name': {'data_type': 'object', 'percentage_missing_value': 0.0},
  'last_name': {'data_type': 'object', 'percentage_missing_value': 0.0},
  'birthplace': {'data_type': 'object',
   'unique_value': [nan,
    'Redding, CA',
    'Detroit, MI',
    'Gainesville, FL',
    'Hickery, North Carolina',
    'Surrey, England',
    'USA',
    'St. Louis, MO',
    'Israel',
    'New York, New York',
    'Copenhagen, Denmark',
    'Kyoto, Japan',
    'Orlando, Florida',
    'Great Neck, New York',
    'Wisconsin',
    'Cedar Falls, Iowa',
    'Pennsylvania',
    'Taipei, Taiwan',
    'Brooklyn, NY',
    'Santa Monica, CA',
    'Haifa, Israel',
    'California',
    'Pittsburgh, PA',
    'Palo Alto CA',
    'Paris, France',
    'Queens, NY',
    'Koblenz, Germany',
    'Switzerland',
    'New York, NY',
    'New Delhi, India',
    'Helsinki, Finland',
    'San Diego, CA',
    'Delft',
    'OHIO',
    'Belfast, Northern Ireland',
    'Dhaka, bangladesh',
    'Braunschweig, Germany',
    'Wayne, New Jersey',
    'Kyiv, Ukraine',
    'Bethlehem, PA',
    'Santa Rosa, CA',
    'Boston',
    'Columbus, OH',
    'New York',
    'Indianapolis, IN USA',
    'Minneapolis',
    'Tours, France',
    'Minneapolis, Minn',
    'Menomenee Falls, WI',
    'Santa Monica CA',
    'Chennai (Tamil Nadu, India)',
    'Boston, MA',
    'Santa Cruz, CA',
    'Stanford, CA',
    'Tampa, FL',
    'Fairbanks, Alaska',
    'Istanbul, Turkey',
    'Los Angeles',
    'Scarborough, N Yorkshire, UK',
    'San Francisco, CA',
    'Rome, Italy',
    'London',
    'Appleton, WI',
    'Chicago, IL',
    'West Virginia',
    'Jammu, India',
    'Las Vegas',
    'Seoul, Korea',
    'Hopatacong, NJ',
    'France',
    'Wollongong, Australia',
    'Liverpool, UK',
    'Milan, Italy',
    'Rimini, Italy',
    'Cambridge',
    'Huntington Beach, California',
    'Washington, DC',
    'The Hague',
    'Netherlands',
    'london',
    'England, UK',
    'Westwood, NJ',
    'New Jersey',
    'Bromma, Stockholm',
    'Huntsville, Alabama',
    'England',
    'Brasi\xadlia, DF, Brasil',
    'Estonia',
    'Tartu, Estonia',
    'Denmark',
    'Sydney, Australia',
    'Prague',
    'US',
    'Philadelphia',
    'Morristown, NJ',
    'San Francisco, California, USA',
    'Deland, FL',
    'Modesto, CA',
    'Portland, OR',
    'Russellville, Ky',
    'California, USA',
    'New Britain, CT',
    'Sofia',
    'Varberg, Sweden',
    'Kuwait',
    'worcester, ma',
    'Mt. Lebanon, PA',
    'New Delhi',
    'Neuilly sur Seine',
    'New York City',
    'Albuquerque, New Mexico, USA',
    'Smithtown, New York',
    'Pasadena, CA',
    'Minneapolis, MN',
    'Brockton, MA',
    'Santa Monica, California',
    'Hollywood, CA',
    'Canada',
    'Sao Paulo, Brazil',
    'Anchorage, Alaska',
    'Springfield, IL',
    'Glasgow, Scotland',
    'South Africa',
    'Centralia, Washington, USA',
    'piranshahr-iran',
    'Media, PA',
    'London, UK',
    'Beverly Hills',
    'Texas',
    'Pittsburgh',
    'yonkers',
    'NY',
    'New Rochelle, New York',
    'Abington, PA',
    'Indiana',
    'Auckland, New Zealand',
    'Portsmouth',
    'Toronto',
    'Virginia, USA',
    'Cork, Ireland',
    'Kobe, Japan',
    'Chicago',
    'Johannesburg, South Africa',
    'South Korea',
    'Alfred, Maine',
    'Glendora, CA',
    'UK',
    'Taiwan',
    'Miami, FL',
    'Copenhagen',
    'Cologne, Germany',
    'Washington DC',
    'Nashua, NH',
    'Metairie, LA',
    'Charlottesville, VA',
    'Los Angeles, CA',
    'State College, PA',
    'Baltimore, MD',
    'Phoenix',
    'Durham NC',
    'Toulouse, France',
    'Tarzana, CA',
    'London England',
    'Wahoo, NE',
    'Bombay, India',
    'NYC',
    'Arlington, Virginia, USA',
    'Boston MA USA',
    'Chicago, Illinois',
    'Windsor Nova Scotia, Canada',
    'c',
    'Spain',
    'San Jose, Costa Rica',
    'Kingston, Jamaica',
    'Blackpool',
    'newplace',
    'Poland',
    'Houston, Texas',
    'Cambridge, Mass.',
    'Buenos Aires, Argentina',
    'Comodoro Rivadavia, Chubut, Argentina',
    'Lutherville-Timonium, Maryland, USA',
    'Hobart, Tasmania',
    'Limoges, France',
    'Espoo, Finland',
    'Longview, WA',
    'Cleveland Heights, Ohio',
    'San Luis Obispo, California, USA',
    'Michigan, USA',
    'Berlin',
    'Stuttgart, Germany',
    'Concord, MA',
    'Tarn Taran, India',
    'Fairhope, AL',
    'Allentown PA',
    'Honolulu HA',
    'Kiev, Ukraine',
    'The Hague, Netherlands',
    'Mississauga, Canada',
    'Valence, France',
    'Hyderabad, India',
    'Des Moines, IA',
    'Tonasket, WA',
    'Easton, PA',
    'israel',
    'Slough',
    'VA',
    'Albany, New York',
    'Florida',
    'Sweden',
    'Sudbury, Ontario, Canada',
    'Tallinn, Estonia',
    'White Plains, NY',
    'london, england',
    'Barcelona',
    'India',
    'Newport Beach, CA',
    'Jerusalem',
    'Iowa',
    'Islamabad',
    'Moscow',
    'Kansas City, MO',
    'Brazil',
    'San Luis Obispo, CA',
    'Belgium',
    'Montreal',
    'Berwick, PA',
    'Argentina',
    'Schenectady, NY',
    'Kansas City, Missouri',
    'Uddevalla, Sweden',
    'Ramat Gan, Israel',
    'Jerusalem, Israel',
    'San Francisco',
    'Germany',
    'Amityville, NY',
    'Hamburg',
    'Dublin, Ireland',
    'Washington, D.C.',
    'Singapore',
    'Oklahoma City',
    'Phoenix, AZ',
    'Amritsar',
    'Odessa, TX',
    'Portugal',
    'Kentucky',
    'Brisbane, Australia',
    'Honolulu, Hawaii',
    'Swidnica',
    'North Carolina',
    'Seattle',
    'CT',
    'Petersburg, IL',
    'Amherst, NY',
    'Massachusetts',
    'Lexington, KY',
    'Melbourne, Australia',
    'Fresno, CA',
    'Youngstown, Ohio',
    'Tampa, FL, USA',
    'Illinois',
    'Greeley, CO',
    'Bekasi',
    'Maryland',
    'San Jose, CA',
    'Falmouth, ME',
    'Osaka, Japan',
    'Austria',
    'Munich',
    'Southern California',
    'River Forest, IL',
    'Bilaspur',
    'Zurich',
    'Cape Town, South Africa',
    'Colorado',
    'Ghent, Belgium',
    'CT, USA',
    'Philadelphia, PA, USA',
    'Lake Forest, CA',
    'Dallas, TX',
    'China',
    'Pueblo, Co',
    'Austin, Texas',
    'Kharkov, Ukraine',
    'Rehovot, Israel',
    'Banaglore',
    'Brooklyn, New York',
    'palmerston Ontario canade',
    'Seattle, WA',
    'Lund, Sweden',
    'Newark, NJ',
    'Ireland',
    'Toledo, Ohio USA',
    'United Kingdom',
    'Berkeley, CA',
    'Ukraine',
    'Narragansett, RI',
    'Lake Wales, FL',
    'Moscow, Russia',
    'Davis, CA',
    'Norway',
    'Seattle, Washington',
    'Portsmouth, NH',
    'Michigan',
    'Lyndhurst, UK',
    'Vienna, Austria',
    'Rouen',
    'Turkey',
    'Brighton, England',
    'Omaha, Nebraska, USA',
    'Huntington, NY',
    'Palo Alto, CA',
    'Ann Arbor, Michigan',
    'PA',
    'Reading, Berkshire, UK',
    'Oxford',
    'Perth, Australia',
    'Akron, OH',
    'Malaysia',
    'Hammond, LA',
    'Manchester, New Hampshire',
    'Kauniainen, Finland',
    'Allentown, PA',
    'Sydney',
    'Detroit',
    'Vancouver',
    'Avigliana, Italy',
    'Tel-Aviv',
    'Lewiston',
    'Morristown, New Jersey, United States',
    'Ann Arbor, Michigan, USA',
    'Baltimore',
    'Tvedestrand, Norway',
    'Washington',
    'Vancouver, Washington',
    'Ceres, South Africa',
    'Minsk, Belarus',
    'Truckee, CA',
    'St. Charles, IL',
    'Houston, TX',
    'Tehran',
    'Chicago, Ill',
    'LA',
    'Paris',
    'Craiova',
    'Ukriane',
    'Eindhoven',
    'Bronx, NY',
    'Guadalajara, Mexico',
    'Ridgewood,NJ',
    'Bastia, France',
    'Junction City, KS',
    'Zimbabwe',
    'New Zealand',
    'Stockholm, Sweden',
    'Park Ridge, IL',
    'Taipei',
    'Gujarat, India',
    'Iran, Tehran',
    'Napa, CA',
    'Pakistan',
    'Edmonton, Alberta',
    'Salinas, CA',
    'Australia',
    'Madrid',
    'Orange County, CA',
    'Delhi',
    'Jacksonville, FL',
    'Milwaukee, WI',
    'Utah',
    'Troy, MI',
    'Bremen, Germany',
    'Biratnagar, Nepal',
    'Coimbra, Portugal',
    'Karl-Marx-Stadt, Germany',
    'Siegen',
    'Jericho, NY',
    'Montreal, Quebec, Canada',
    'Tehran, Iran',
    'Beijing, China',
    'London, England',
    'MalmÃ¶, Sweden',
    'Philadelphia Pa',
    'Buffalo, NY',
    'MA',
    'East Meadow, NY',
    'Helena, Montana',
    'Korea',
    'Huáº¿, Viá»\x87t-Nam',
    'Hillsdale, NJ',
    'Omaha, NE',
    'ljubljana, slovenia',
    'Woonsocket, RI',
    'San Antonio, TX',
    'Leningrad, USSR',
    'Nice, France',
    'Brussels',
    'shanghai',
    'Santiago, Chile',
    'Philadelphia, PA',
    'Tullamore, IE',
    'Brno, Czech Republic',
    'Ashford, Kent, UK',
    'Wellington, New Zealand',
    'Edmonton, AB',
    'Goshen, IN',
    'Plano, Texas, USA',
    'Atlanta, Georgia',
    'Stockholm',
    'Vienna',
    'Atlanta, GA',
    'Columbus, GA',
    'Lachine, Canada',
    'Boca Raton, FL',
    'Dublin',
    'Northampton',
    'Bucharest',
    'Des Moines, Iowa',
    'Hong Kong',
    'New Bedford, MA',
    'Portsmouth, UK',
    'Glen Cove, New York',
    'Watertown, CT',
    'Bethesda',
    'Cannon Falls, MN',
    'Milwaukee, Wisconsin',
    'Connecticut',
    'Minnesota',
    'Cleveland',
    'Dordrecht',
    'Johannesburg',
    'Edinburgh',
    'The Netherlands',
    'Scotland',
    'Princeton, NJ',
    'berkeley',
    'Tianjin, China',
    'Surrey, UK',
    'Birmingham, UK',
    'Grammichele (CT) Italia',
    'Yerevan, Armenia',
    'Bratislava, Slovakia',
    'Lancashire, UK',
    'Urbana',
    'Phoenix Arizona',
    'Memphis, TN',
    'Winnipeg, Canada',
    'Somerville, Mass.',
    'Hamilton, Canada',
    'Meriden Connecticut',
    'Istanbul',
    'Karachi,Pakisatn',
    'Pensacola, FL',
    'Cleveland, Ohio',
    'Kinshasa',
    'Rio Grande, Brazil',
    'United States',
    'Kennebunkport, Maine',
    'City of New York',
    'Tokyo',
    'Chennai, India',
    'birmingham',
    'Rochester, MN',
    'Rochester, NY',
    'Quebec, Canada',
    'Anaheim, CA, USA',
    'Evanston, IL',
    'Novosibirsk, Russia',
    'South Carolina',
    'Toronto, Canada',
    'Burlington, VT',
    'Virginia',
    'knoxville',
    'Rockville, Maryland',
    'Bellflower, CA',
    'Lisboa, Portugal',
    'Boise, ID',
    'Melrose, MA',
    'Lille',
    'Neptune, New Jersey, USA',
    'Barberton, Ohio',
    'Patna',
    'Boise ID',
    'Charleston, SC',
    'Barcelona, Spain',
    'Bonn, Germany',
    'Munich, Germany',
    'Edmonton, Canada',
    'Hemet, California',
    'Langenfeld',
    'Northridge, California',
    'Sherman Oaks, CA',
    'Orange, CA',
    'Newton MA',
    'Louisville, KY',
    'Nashville, TN',
    'Sligo, Ireland',
    'Poznan, Poland',
    'Liverpool',
    'Boston, Mass.',
    'Pico Rivera, California',
    'Ede, The Netherlands',
    'Slovakia',
    'Bangalore, India',
    'South Bend, Indiana, USA',
    'Athens, Greece',
    'Amsterdam, The Netherlands',
    'rajasthan, india',
    'Karlsruhe',
    'Lowell, MA',
    'Pachmari, Madhya Pradesh, India',
    'Sacramento, CA',
    'Peoria, IL',
    'Canberra',
    'Wales',
    'Maine',
    'Chennai',
    'Idaho Falls ID',
    'Los Angeles, California',
    'Tampa Bay,FL',
    'New York City, New York, USA',
    'Marathon, FL',
    'Belleville, Ontario, Canada',
    'San Jose',
    'Los Altos',
    'Tramore, Co. Waterford, Ireland',
    'Ann Arbor, MI',
    'Atlanta',
    'Norwalk, CT',
    'Harbor City, CA',
    'Greenville, NC',
    'Vancouver, Canada',
    'Augusta, GA',
    'Toronto, Ontario',
    'Kapuskasing, Ontario, Canada',
    'Frankfurt',
    'Asse, Belgium',
    'Halifax, UK',
    'Austin, TX',
    'Santa Clara, CA',
    'Harrogate, UK',
    'Bergen, Norway',
    'Antwerp',
    'Otaniemi, Finland',
    'INDIA',
    'Bayport, NY',
    'Ohio',
    'Manhattan Beach, CA',
    'Japan',
    'Tacoma, WA',
    'Illinois, USA',
    'Manilla',
    'Vineland, NJ',
    'Janesville, WI',
    'Hamburg, Germany',
    'Pune, India',
    'Uruguay',
    'Boston, Massachusetts',
    'Oahu, HI',
    'Calgary, Alberta, Canada',
    'Boston, USA',
    'Bonn',
    'Eugene, OR',
    'Kanhangad',
    'Nova Scotia',
    'El Paso, TX',
    'Madrid, Spain',
    'Essen',
    'Youngstown',
    'Tacoma',
    'Turnhout, Belgium',
    'Carbondale, PA',
    'Perth, Western Australia',
    'Havre de Grace, Maryland, USA',
    'Torrance, California, USA',
    'Peru, IN',
    'Langerak',
    'Miami, Florida',
    'Vietnam',
    'Fort Wayne, IN',
    'Canton',
    'Toledo, Ohio',
    'Dearborn, MI',
    'Ohio, USA',
    'Pennsylvania, USA',
    'Capital Federal | Buenos Aires | Argentina',
    'Novi Sad',
    'Giubiasco, Switzerland',
    'Finland',
    'Geneva, Switzerland',
    'Warendorf, germany',
    'Cologne',
    'Moline, IL',
    'Tulsa, Oklahoma',
    'Prince George, BC, Canada',
    'Leeuwarden, The Netherlands',
    'Fort Belvoir, VA',
    'Anderson, IN',
    'Gosford',
    'North Vancouver',
    'Oakland, Ca',
    'Jaffna, Sri Lanka',
    'Honolulu, HI',
    'Bangladesh',
    'Bellevue, Washington',
    'Leicester, England',
    'Rome - Italy',
    'Windsor, Ontario',
    'NYC, NY',
    'Belfast',
    'Whitefish Bay, WI',
    'Manchester',
    'Worcester,MA',
    'Edmonton',
    'Douglas, Isle of Man, UK',
    'Dnepropetrovsk, Ukraine',
    'Miami',
    'Newnan, Georgia',
    'Mumbai',
    'Oxford, UK',
    'Amsterdam',
    'Nagpur',
    'Bilbao, Spain',
    'Karachi',
    'maryland',
    'Cochin',
    'Galway, Ireland',
    'Mississauga, Ontario',
    'Graz',
    'Dallas',
    'Charlotte, NC',
    'Braga, Portugal',
    'Sylhet, Bangladesh',
    'Versailles, OH',
    'Vancouver, BC, Canada',
    'Jamaica',
    'Alcoy',
    'Salt Lake City, Utah',
    'rio de janeiro',
    'Livingston, NJ',
    'Brasil',
    'Konstanz, Germany',
    'Malmo, Sweden',
    'Marseille, France',
    'Mpls, MN',
    'Pisa, Italy',
    'Buenos Aires',
    'Tanjay City, Negros Oriental Philippines',
    'Maldives',
    'Beirut, Lebanon',
    'Lisbon, Portugal',
    'Somerset, Massachusetts',
    'Cagliari',
    'Kerala,India',
    'Calicut',
    'kasaragod',
    'Zaria, Nigeria',
    'Kazan, Russia',
    'Pekin, IL',
    'Denver,  CO USA',
    'Augsburg, Germany',
    'DAHANU, THANE, MAHARASHTRA, INDIA',
    'Nellore',
    'amsterdam',
    'Adelaide, Australia',
    'Kelheim',
    'Tel Aviv',
    'Meerut',
    'San Diego',
    'Vienna, VA',
    'Edinburgh, Scotland',
    'Laport Ind',
    'Busan',
    'Denville, NJ',
    'Chester, UK',
    'Bakersfield, California',
    'shihua',
    'Ashland, OR',
    'Assisi, Italy',
    'Jakarta, Indonesia',
    'Bochum',
    'Oberhausen',
    'Falmouth, MA',
    'Massapequa, NY',
    'Georgia, USA',
    'Iron Mountain, MI',
    'Da Nang, Vietnam',
    'Guangdong, China',
    'Naples',
    'MD, USA',
    'Uppsala',
    'Romania',
    'Manila, Philippines',
    'Rio de Janeiro, Brazil',
    'Kansas City',
    'Norwood,New Jersey',
    'bali',
    'Madison Wisconsin',
    'ISRAEL',
    'Tashkent, Uzbekistan',
    'Rotterdam',
    'East Islip, NY',
    'Bucharest, Romania',
    'Napoli, Italy',
    'Reykjavik, Iceland',
    'Gdynia, Poland',
    'St. Louis',
    'Newton, Mass',
    'Stamford, CT',
    'Cleveland, Ohio, USA',
    'Ontario, Canada',
    'St. Gallen, Switzerland',
    'Newcastle-upon-Tyne',
    'Washington D.C.',
    'Beverly Hills, CA',
    'Milwaukee',
    'Jamestown, RI',
    'Timisoara/Romania',
    'Brisbane',
    'Emmen, the Netherlands',
    'Saint Joseph, Missouri',
    'Arad, Romania',
    'Sedona, AZ',
    'New Hampshire',
    'Kelowna',
    'Lebanon',
    'Dhahran, Saudi Arabia',
    'CA',
    'Morocco',
    'Misawa, Japan',
    'Cairo, Egypt',
    'Dallas, Texas',
    'Harrow, London',
    'Suffern, NY',
    'McLean, VA',
    'La Honda, California',
    'Grenoble',
    'San Anselmo, CA',
    'Saint Charles, IL',
    'Hyderadab',
    'Tacoma, Washington',
    'Basel',
    'Freiburg, Germany',
    'Beaumont, Texas',
    'adoni',
    'Guines, Cuba',
    'Seattle Washington, USA',
    'mysoor',
    'Milan',
    'New Orleans',
    'Kamakura, Japan',
    'Willingboro, NJ',
    'Ottawa, Canada',
    'Patan, Gujarat, India',
    'Teofilo Otoni, MG, Brazil',
    'Caldwell, Idaho',
    'Royal Oak, MI',
    'Fairmont, WV',
    'Queens, New York',
    'Vallejo, CA',
    'U.S.',
    'Norwood, MA',
    'Tosu, Japan',
    'Colne',
    'Paradise, CA',
    'Renton, Washington',
    'Manhattan',
    'Eygpt',
    'Amman - Jordan',
    'Italy',
    'lodo',
    'Monongahela, PA',
    'Russia',
    'DeKalb, IL',
    'Goa',
    'Strasbourg, France',
    'Oneonta, NY',
    'Saint Louis , MO',
    'montreal, quebec',
    'Grand Rapids, MI',
    'Hampton, VA',
    'Liverpool, The UK',
    'Osaka',
    'Kochi',
    'Hawaii',
    'Gothenburg, Sweden',
    'Neyveli',
    'Frankston',
    'Rosario',
    'Winnipeg',
    'Constance, Germany',
    'Glen Cove, NY',
    'Long Beach, CA',
    'Bowling Green, OH',
    'Amsterdam, the Netherlands',
    'Eskisehir, Turkey',
    'Chipping Norton, UK',
    'Gainesville, Florida',
    'Irvine, Scotland',
    'American Fork, Utah',
    'Hyderabad',
    'Rio de Janeiro - RJ - Brazil',
    'Newport Beach',
    'Saratoga, CA',
    'Princeton, MA',
    'Portchester, NY',
    'Lexington, SC',
    'Los Altos, CA',
    'Chapel Hill, NC',
    'Aberdeen, Scotland',
    'San Remo - Italy',
    'Syracuse, NY',
    'Lyon, France',
    'Bangalore',
    'Orlando, FL',
    'Thiruvananthapuram',
    'Amersfoort, The netherlands',
    'Brighton UK',
    'Atlanta, GA USA',
    'Turku, Finland',
    'Staten Island, New York',
    'Pathankot',
    'Chandigarh',
    'Portsmouth, England',
    'chicago',
    'Nicaragua',
    'Madurai',
    'Fort Wayne, Indiana, USA',
    'Montreal, Canada',
    'Melbourne',
    'Denver, CO',
    'Jupiter, FL',
    'Bogota, Colombia',
    'East Hampton, NY',
    'Guwahati',
    'Cleveland, OH',
    'Amman',
    'Cleburne Texas',
    'Saarlouis, Germany',
    'Maine, USA',
    'Azerbaijan, Baku',
    'Wellington',
    'Bern',
    'Puri, Orissa, India',
    'Madera, CA',
    'The Office, CA',
    'Tokyo, Japan',
    'Sacramento,CA',
    'Carlow',
    'Grenoble, France',
    'Gloucester',
    'Leuven',
    'Ozora',
    'Chicago IL',
    'Harrisburg, PA',
    'Benoni',
    'Bradford, UK',
    'Kymmerer, Wyoming',
    'BogotÃ¡, Colombia',
    'Verona',
    'Mysore',
    'Robbinsdale, MN',
    'Portland Maine',
    'Veliko Tarnovo, Bulgaria',
    'Chile',
    'Prince Edward Island',
    'Leipzig, Germany',
    'Marion, VA',
    'Kent',
    'Ndola, Zambia',
    'NynÃ¤shamn, Sweden',
    'Rome, italy',
    'Torino',
    'Brzesko',
    'Northern Ireland',
    'Bern, Switzerland',
    'Leuven, Belgium',
    'Indianapolis',
    'Portland Oregon',
    'Palo Alto',
    'Van Nuys, CA',
    'Neuss',
    'Skopje',
    'Torino, Italy',
    'Colorado Springs, CO',
    'Kirsehir, Turkey',
    'Nottingham, England',
    'St. Anthony, Idaho',
    'Corvallis, OR',
    'Kuala Lumpur, Malaysia',
    'Bishkek',
    'Cork,Ireland',
    'Pasadena',
    'Grand Rapids, MI, United States',
    'Worcester, MA',
    'Harlem USA',
    'Thunder Bay',
    'Bellingham, Wa',
    'Cuba',
    'North America',
    'Varanasi, India',
    'Russia, Rostov-on-Don',
    'Siberia, Russia',
    'Bristol, United Kingdom',
    'Natal Brasil',
    'Lithuania',
    'MatarÃ³ (Barcelona)',
    'Passaic, NJ',
    'Yamuna Nagar, Haryana',
    'Ft. Dix, New Jersey, USA',
    'Oklahoma City, OK',
    'Geelong, Australia',
    'Houston, TX, US',
    'Ladysmith, South Africa',
    'Duesseldorf',
    'Indio, CA',
    'Karachi, Pakistan',
    'Bay Area',
    'Warren, Ohio, USA',
    'Patna, India',
    'Cape Town',
    'san jose,ca',
    'Oakland, CA',
    'Salon de Provence',
    'Bristol',
    'sion',
    'new york city',
    'South Pasadena, CA',
    'Mangalore',
    'Belfast, NI',
    'istanbul',
    'Hibbing, Minnesota, USA',

## Profiling Data Relationship

In [70]:
# Profiling Table relationships
df_relationships = extract_database('relationships')

# create profiling object
relationships_profiling = Profiling(data = df_relationships, table_name='relationships')

# get columns from the table
relationships_profiling.get_columns()

['created_at',
 'end_at',
 'is_past',
 'person_object_id',
 'relationship_id',
 'relationship_object_id',
 'sequence',
 'start_at',
 'title',
 'updated_at']

In [72]:
# Profiling Table fact_relationships
df_fact_relationships = extract_database('fact_relationships',db_name='warehouse')

# create profiling object
fact_relationships_profiling = Profiling(data = df_fact_relationships, table_name='fact_relationships')

# get columns from the table
fact_relationships_profiling.get_columns()

['relationship_id',
 'relationship_nk',
 'people_id',
 'company_id',
 'title',
 'start_at',
 'end_at',
 'relationship_status',
 'relationship_order',
 'created_at']

In [79]:
df_relationships['is_past'].value_counts()

is_past
FALSE    134726
Name: count, dtype: int64

In [77]:
df_fact_relationships

,relationship_id,relationship_nk,people_id,company_id,title,start_at,end_at,relationship_status,relationship_order,created_at
0,1,130852,117250,26943,None,21000101,21000101,Current,3,2025-07-29 16:49:40.183116+00:00
1,2,61805,203367,9575,None,21000101,21000101,Current,2,2025-07-29 16:49:40.183116+00:00
2,3,95412,216818,48574,Co-Founder,21000101,21000101,Current,1,2025-07-29 16:49:40.183116+00:00
3,4,95938,217040,48749,CEO,20120109,21000101,Current,1,2025-07-29 16:49:40.183116+00:00
4,5,96463,136171,14934,"CEO, Founder",20100701,21000101,Current,4,2025-07-29 16:49:40.183116+00:00
...,...,...,...,...,...,...,...,...,...,...
134721,134722,93216,103500,47612,President & CEO,21000101,21000101,Current,1,2025-07-29 16:49:40.183116+00:00
134722,134723,93506,103624,47774,Business Development,20100201,20120201,Current,1,2025-07-29 16:49:40.183116+00:00
134723,134724,93791,103755,414,.NET Developer,20091001,20110601,Current,1,2025-07-29 16:49:40.183116+00:00
134724,134725,94511,104038,48247,None,21000101,21000101,Current,1,2025-07-29 16:49:40.183116+00:00
134725,134726,94750,104130,48308,VP Business Development,21000101,21000101,Current,1,2025-07-29 16:49:40.183116+00:00

In [80]:
df_relationships.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134726 entries, 0 to 134725
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   created_at              134726 non-null  object
 1   end_at                  19254 non-null   object
 2   is_past                 134726 non-null  object
 3   person_object_id        134726 non-null  object
 4   relationship_id         134726 non-null  object
 5   relationship_object_id  134726 non-null  object
 6   sequence                134726 non-null  object
 7   start_at                62678 non-null   object
 8   title                   129303 non-null  object
 9   updated_at              134726 non-null  object
dtypes: object(10)
memory usage: 10.3+ MB

In [82]:
df_fact_relationships.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134726 entries, 0 to 134725
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   relationship_id      134726 non-null  int64
 1   relationship_nk      134726 non-null  int64
 2   people_id            134726 non-null  int64
 3   company_id           134726 non-null  int64
 4   title                129303 non-null  object
 5   start_at             134726 non-null  int64
 6   end_at               134726 non-null  int64
 7   relationship_status  134726 non-null  object
 8   relationship_order   134726 non-null  int64
 9   created_at           134726 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), int64(7), object(2)
memory usage: 10.3+ MB

In [41]:
# create profiling object
relationships_profiling = Profiling(data = df_relationships, table_name='relationships')

# Set Profiling Rule
# list check data type (all columns)
data_type_column = relationships_profiling.get_columns()

#list check unique values
unique_values_column = []

#list check percentage missing values
missing_values_column = ['start_at','end_at','title']

#list check valid date values
valid_date_column = ['start_at','end_at']

# Set Profiling rule to object
relationships_profiling.selected_columns(data_type_column, unique_values_column, missing_values_column, valid_date_column)

In [ ]:
# Create Reporting Profiling
report_relationships = relationships_profiling.reporting()
report_relationships

['created_at',
 'description',
 'milestone_at',
 'milestone_code',
 'milestone_id',
 'object_id',
 'source_description',
 'source_url',
 'updated_at']

# API

## Profiling Data Milestones

In [85]:
# Profiling Table milestones
df_milestones = extract_database('milestones')

# create profiling object
milestones_profiling = Profiling(data = df_milestones, table_name='milestones')

# get columns from the table
milestones_profiling.get_columns()

['created_at',
 'description',
 'milestone_at',
 'milestone_code',
 'milestone_id',
 'object_id',
 'source_description',
 'source_url',
 'updated_at']

In [88]:
# Profiling Table fact_milestones
df_fact_milestones = extract_database('fact_milestones',db_name='warehouse')

# create profiling object
fact_milestones_profiling = Profiling(data = df_fact_milestones, table_name='fact_milestones')

# get columns from the table
fact_milestones_profiling.get_columns()

['milestone_id',
 'milestone_nk',
 'company_id',
 'milestone_at',
 'description',
 'milestone_code',
 'created_at']

In [86]:
df_milestones

,created_at,description,milestone_at,milestone_code,milestone_id,object_id,source_description,source_url,updated_at
0,2010-09-23 04:10:33.000,Raised 11M Series A financing,2008-08-10,other,7164,c:51693,Brammo Raises Series A for Electric Motorcycle,http://venturebeat.com/2008/09/20/brammo-raise...,2010-09-24 18:12:58.000
1,2008-08-12 01:45:34.000,YuMe Brings in Michael Mathieu as New CEO,2008-08-11,other,345,c:1063,New CEO For YuMe,http://www.techcrunch.com/2008/08/11/new-ceo-f...,2008-08-12 01:45:56.000
2,2008-12-01 13:29:10.000,Event Innovation Appoints Frank Ganis VP of Bu...,2008-08-11,other,814,c:8941,Event Innovation Appoints Frank Ganis VP of Bu...,http://www.eventinnovation.com/081108pressrele...,2008-12-02 00:08:44.000
3,2012-02-10 05:05:23.000,"Investment in Invite Media, Inc.",2008-08-11,other,18297,f:8660,None,None,2012-02-11 08:23:53.000
4,2012-07-08 17:05:02.000,Founded,2012-04-15,other,21376,c:157894,None,None,2012-07-09 17:07:44.000
...,...,...,...,...,...,...,...,...,...
27010,2013-11-07 17:23:34.000,Tram Ho is now Investor Relations Director at ...,2013-08-01,other,37743,f:14066,None,None,2013-11-08 00:40:40.000
27011,2013-11-26 22:09:35.000,Tengram Capital Partners acquired DevaCurl.,2013-11-26,other,38691,f:9806,None,http://www.mydevacurl.com,2013-11-26 22:09:35.000
27012,2013-11-04 21:04:57.000,Top50 of the Million Pound Startup!,2013-11-04,other,37522,c:236715,None,None,2013-11-05 03:39:03.000
27013,2013-11-06 14:00:12.000,1-2-3.tv live-auction goes mobil with iPad-App,2013-10-15,other,37657,c:144602,None,http://www.1-2-3.tv,2013-11-06 18:23:26.000
27014,2013-11-28 17:12:43.000,Litetree passes the 9000 active trader mark.,2013-11-28,other,38805,c:223429,None,None,2013-11-29 03:30:48.000

In [89]:
df_fact_milestones

,milestone_id,milestone_nk,company_id,milestone_at,description,milestone_code,created_at
0,1,11553,31232,20090101,Aabar Joins Forces With Berndorf in New Joint ...,other,2025-07-29 16:48:07.502278+00:00
1,2,12099,13071,20110409,My Outdoor Calendar launches with new product....,other,2025-07-29 16:48:07.502278+00:00
2,3,12210,67858,20110402,"Stigasoft, continuing the trend to explore new...",other,2025-07-29 16:48:07.502278+00:00
3,4,12275,49160,20110419,"Campus.com, a top online textbook retailer, un...",other,2025-07-29 16:48:07.502278+00:00
4,5,12277,49160,20110228,"eCampus.com, a top online textbook retailer, r...",other,2025-07-29 16:48:07.502278+00:00
...,...,...,...,...,...,...,...
27010,27011,6853,44239,20100527,ASUS selects Syncables Desktop to be bundled ...,other,2025-07-29 16:48:07.502278+00:00
27011,27012,7212,45066,20100710,SupportSquad strike sponsorship deal with Phil...,other,2025-07-29 16:48:07.502278+00:00
27012,27013,9477,29909,20110103,"OVER 100,000 VIEWS WITH NEARLY 2,000 PER DAY O...",other,2025-07-29 16:48:07.502278+00:00
27013,27014,9767,3665,20110114,Agilis Systems Leaps onto the Android Platform,other,2025-07-29 16:48:07.502278+00:00
27014,27015,9832,1838,20110117,Experian Buys In To Social Media Marketing,other,2025-07-29 16:48:07.502278+00:00

In [91]:
df_milestones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27015 entries, 0 to 27014
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   created_at          27015 non-null  object
 1   description         27015 non-null  object
 2   milestone_at        27015 non-null  object
 3   milestone_code      27015 non-null  object
 4   milestone_id        27015 non-null  object
 5   object_id           27015 non-null  object
 6   source_description  21288 non-null  object
 7   source_url          22616 non-null  object
 8   updated_at          27015 non-null  object
dtypes: object(9)
memory usage: 1.9+ MB

In [92]:
df_fact_milestones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27015 entries, 0 to 27014
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   milestone_id    27015 non-null  int64
 1   milestone_nk    27015 non-null  int64
 2   company_id      27015 non-null  int64
 3   milestone_at    27015 non-null  int64
 4   description     27015 non-null  object
 5   milestone_code  27015 non-null  object
 6   created_at      27015 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), int64(4), object(2)
memory usage: 1.4+ MB

In [ ]:
# create profiling object
milestones_profiling = Profiling(data = df_milestones, table_name='milestones')

# Set Profiling Rule
# list check data type (all columns)
data_type_column = milestones_profiling.get_columns()

#list check unique values
unique_values_column = []

#list check percentage missing values
missing_values_column = ['source_description','source_url','milestone_at']

#list check valid date values
valid_date_column = ['milestone_at']

# Set Profiling rule to object
milestones_profiling.selected_columns(data_type_column, unique_values_column, missing_values_column, valid_date_column)

In [ ]:
# Create Reporting Profiling
report_milestones = milestones_profiling.reporting()
report_milestones

{'created_at': '2025-04-06', 'report': {'created_at': {'data_type': 'object'}, 'description': {'data_type': 'object'}, 'milestone_at': {'data_type': 'object', 'percentage_missing_value': 0.0, 'percentage_valid_date': 100.0}, 'milestone_code': {'data_type': 'object'}, 'milestone_id': {'data_type': 'int64'}, 'object_id': {'data_type': 'object'}, 'source_description': {'data_type': 'object', 'percentage_missing_value': 22.8}, 'source_url': {'data_type': 'object', 'percentage_missing_value': 17.92}, 'updated_at': {'data_type': 'object'}}}

{'created_at': '2025-04-06',
 'report': {'created_at': {'data_type': 'object'},
  'description': {'data_type': 'object'},
  'milestone_at': {'data_type': 'object',
   'percentage_missing_value': 0.0,
   'percentage_valid_date': 100.0},
  'milestone_code': {'data_type': 'object'},
  'milestone_id': {'data_type': 'int64'},
  'object_id': {'data_type': 'object'},
  'source_description': {'data_type': 'object',
   'percentage_missing_value': 22.8},
  'source_url': {'data_type': 'object', 'percentage_missing_value': 17.92},
  'updated_at': {'data_type': 'object'}}}